### ISSUE TITLE
Device does not update kWh

### ISSUE THREAD

**Issue by Allram** [gruijter/com.gruijter.powerhour#10]
One of my devices does not update the values for kWh until I restart the app.
It's a virtual device, but my other virtual devices does work. Tried to remove and add it again, but get the same problem.

The device name is: Vårt strømforbruk
Report I'd: d2e3ad0d-9443-457f-9032-ae31e594a27b
Running version: 3.1.0

**Comment by gruijter** [comment]
I dont see any errors in the log you sent. So all seems ok. I see you have an interval set at 5 minutes. Did you already try setting that to 0? That uses a different method to updatebthe values.

**Comment by Allram** [comment]
That seems to have fixed it. Will let it run for a few hours and see if it locks up again.
Thanks for the tip :)

**Comment by Allram** [comment]
Closing issue as setting the interval to 0 minutes fixed the problem.
