### ISSUE TITLE
DAP Error after 5.1.1 upgrade

### ISSUE THREAD

**Issue by ECKEROTH** [gruijter/com.gruijter.powerhour#100]
Will upload pictures tomorrow
“No compatible meter_power capability”
0b5b88d3-f774-48e8-b0f6-b0e849479b90

![IMG_1511](https://user-images.githubusercontent.com/10584519/211491488-32fb7a2e-e32b-4e6a-bc24-a53dfed9e05c.PNG)
![IMG_1512](https://user-images.githubusercontent.com/10584519/211491497-1ff19ca2-b818-47e7-857f-6e01f762fe9e.PNG)

**Comment by Bosse64** [comment]
I have the same problem

**Comment by ECKEROTH** [comment]
Update 5.1.2 still have same issue.
3521157b-9fe9-4f1a-b46b-86eee8a18761
“no compatible meter_power capability”

**Comment by gruijter** [comment]
See instructions here https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/1248

**Comment by gruijter** [comment]
fixed in v5.0.4
Problem was with summarizer devices set to polling mode
