### ISSUE TITLE
My Energy cost exploded overnight, howcome?

### ISSUE THREAD

**Issue by dacootmeister** [gruijter/com.gruijter.powerhour#102]
Hi Robin,

I noticed in Homey that my energy cost exploded overnight and I cant figure out why/how?
Value for kWh exploded, therefore also cost

![image](https://user-images.githubusercontent.com/35705080/212620577-822427d1-f20f-4463-afc3-69adf0d6e542.png)

0.71 kWh
27 minuten geleden
0.21 kWh
kWh dit uur
18.46 kWh
kWh vorige dag
**8399.53 kWh**
kWh deze dag
353.31 kWh
kWh vorige maand
**8573.82 kWh**
kWh deze maand
-
kWh vorig jaar
**8272.58 kWh**
kWh dit jaar
4854.8%
Op budget Maand Zover
459.2%
Op budget Jaar Zover
0.55 €
Geld vorig uur
0.16 €
Geld dit uur
14.24 €
Geld vorige dag
**6479.15 €**
Geld deze dag
**272.53 €**
Geld vorige maand
**6613.56 €**
Geld deze maand
-
Geld vorig jaar
7024.84 €
Geld dit jaar
0.7714 €
Actief tarief
10286.82 kWh
Energie
450 Watt
Vermogen
16-01 00:00
Min/Max Sinds
225 Watt
Minimum
251398972 Watt

I'm running 5.1.4 of the app. 
Any advise where to look for?

**Comment by gruijter** [comment]
look at the source app/device. if the kWh has exploded there, it will also explode in PBTH ;)

**Comment by dacootmeister** [comment]
Yes, strange but it seems to have been fixed automagically......, although some values still skyrocket.

![image](https://user-images.githubusercontent.com/35705080/212775563-42087166-a7e7-4926-ab7e-dd4fe3160442.png)

0.42 kWh
kWh vorig uur
0.27 kWh
kWh dit uur
18.46 kWh
kWh vorige dag
13.27 kWh
kWh deze dag
353.31 kWh
kWh vorige maand
187.56 kWh
kWh deze maand
-
kWh vorig jaar
-113.68 kWh
kWh dit jaar
106.2%
Op budget Maand Zover
-6.3%
Op budget Jaar Zover
0.32 €
Geld vorig uur
0.21 €
Geld dit uur
14.24 €
Geld vorige dag
10.24 €
Geld deze dag
272.53 €
Geld vorige maand
144.66 €
Geld deze maand
-
Geld vorig jaar
555.94 €
Geld dit jaar
0.7714 €
Actief tarief
1900.56 kWh
Energie
480 Watt
Vermogen
16-01 00:00
Min/Max Sinds
**-176186391 Watt**
Minimum
**251398972 Watt**
21 uur geleden

**Comment by VitaliBabkin** [comment]
hello,
the same story
![image](https://user-images.githubusercontent.com/20084345/213117192-282f3940-211e-485c-bb3d-1a5f6c13a1ca.png)

![image](https://user-images.githubusercontent.com/20084345/213117157-b1da2ab4-5c7a-484d-95ad-0527b14c9e91.png)

**Comment by gruijter** [comment]
Yes there is a big dip in the source kWh.  So why do you report that problem as a PBTH issue?

**Comment by dacootmeister** [comment]
@gruijter indeed its not a PBTH issue, but it makes it visible immediately in cost that a hickup is coming from the P1 port.
Check your graphs @VitaliBabkin 
![image](https://user-images.githubusercontent.com/35705080/213158981-77dff0c9-8de3-4569-bb7c-7933e4369a7e.png)

**Comment by VitaliBabkin** [comment]
I am confused that, for example, the data changes by 3k when the application is restarted, but there is no such jump in the energy graph.
![image](https://user-images.githubusercontent.com/20084345/213291173-e7b793ca-95b6-4c01-ae85-dd0de6983496.png)


I am changing the logic and will collect the data with a script to check that the data is derived from three phases and greater than the previous value.

**Comment by ameesme** [comment]
Sorry, to clarify: the graph I shared was from the actual energy meter, not PBTH.

**Comment by gruijter** [comment]
@VitaliBabkin yes that is weird. Are you sure you are not using watts as source?

**Comment by VitaliBabkin** [comment]
> @VitaliBabkin yes that is weird. Are you sure you are not using watts as source? Or have you enabled source resets to 0 maybe?

I use kWh, I use a solar panel from Virtual Device App as a total meter.  
After a little testing, I see that getting data from the 3EM meter is better with a script where I can comfortably check the values. my old version and it also worked fine until the situation above
![image](https://user-images.githubusercontent.com/20084345/215314309-aeb33ac2-0774-4caf-9351-675b9cc814bc.png)
