### ISSUE TITLE
Night price no longer applies

### ISSUE THREAD

**Issue by kmengvik** [gruijter/com.gruijter.powerhour#103]
Recently the day price is set 24/7. Should alter at 0600 and 2200 hrs. Assume a recent update has gone bad
![image](https://user-images.githubusercontent.com/16176305/213915570-9c04307d-c5a1-430d-af52-97817c05404d.png)

also, apparently the DAP today JSON has not been delivered the last two days. Only The "when new prices for tomorrow" seem to work now.

EDIT: The today JSON came through this midnight. Only the day/night price issue is persistent.

**Comment by gruijter** [comment]
will be fixed in the next release. Thx for reporting!

**Comment by gruijter** [comment]
fixed in v5.4.0 https://homey.app/a/com.gruijter.powerhour/test

**Comment by kmengvik** [comment]
thnx, testing now
