### ISSUE TITLE
Gas usage Today shows wrong amount (includes previous day)

### ISSUE THREAD

**Issue by haandrw** [gruijter/com.gruijter.powerhour#108]
Hi, not sure if this is related to the update just done, but my gas usage for today is way off and seems to still include the usage of yesterday. For Power used today there is no issue.

**Comment by gruijter** [comment]
could be. see forum for background. 
https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/1346
