### ISSUE TITLE
Tuya smart plugs fail since update to version 5.4.3

### ISSUE THREAD

**Issue by BertWi** [gruijter/com.gruijter.powerhour#110]
Hi Robin,

all my Tuya cloud smart plugs now fail in PBTH with the message "no compatible meter_power capabilities onoff, measure_power". This happened since the upgrade to version 5.4.3 at 6 Feb 12:20 (on my Homey). Version 5.4.4 did not solve it either. Please help.

Thanks!

**Comment by gruijter** [comment]
https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/1391

**Comment by BertWi** [comment]
Thanks! Works again. The kind of issues a simple space in the wrong place can do ;-) Thanks for the lovely work you are doing!

**Comment by BertWi** [comment]
Forgot the close the issue.
