### ISSUE TITLE
Support for InfluxDb Homey App?

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [gruijter/com.gruijter.powerhour#112]
There is an app [InfluxDb](https://homey.app/nl-nl/app/homey.influxdb/InfluxDb/) for Homey, I run this because in the past Homey Insights failed me and Grafana dashboards cannot be created from Homey insight.

I have PbtH and Influx both running, but I see that InfluxDb does not export the numeric variables of PbtH, presumable because these are not values from devices. Probably not only PbtH, but maybe also InfluxDb need additional code.  

Please look into it, I would love to use the numeric values from PbtH saved in InfluxDb and use them in Grafana dashboards. 
Thanks in advance.

**Comment by gruijter** [comment]
This you need to take up with the developer of the InfluxDb app ( @balmli )  . He could add listeners for the homey values that you are interested in.
But when I look at the description from the InfluxDB app you should be able to send any value to it via a flow. So no need for any dev to achieve what you want probably ;)
