### ISSUE TITLE
Summarize does not work

### ISSUE THREAD

**Issue by Svensson78** [gruijter/com.gruijter.powerhour#122]
Summarizer does not work for 10 days now.
So my flow, which get export the totals every night in an Google sheet, does not work anymore!

**Comment by gruijter** [comment]
all my summarizers still work. So it must be you ;)

Maybe some more details would help.
What is the source app?
Is the source device online?
Did you try to delete the summarizer and add it again?
What else did you already try?

**Comment by Svensson78** [comment]
Sorry really dumb from me due to new router the ip adres of the Plugwise changed although I set an fixed ip adres! Now everything works again! I did tried everything thing and due to you’re quick answer I looked further so you did help me!
