### ISSUE TITLE
Support for sold Power in PBTH

### ISSUE THREAD

**Issue by kia1015** [gruijter/com.gruijter.powerhour#127]
Hi,
I would like to be able to have a virtual device fetching data from Tibber pulse and summing up the sold power that I have generated through my solar panels. 
I have tried to create this kind of device, but looks like the negative power is not registered. 
Are there any plans to add this kind of support?
I have added an image of the registered power from Tibber pulse and from the virtual device I created in PBTH. 
![image](https://github.com/gruijter/com.gruijter.powerhour/assets/113135092/26baf39f-c215-47f6-94b6-af7a29af487e)
/Kristina

**Comment by gruijter** [comment]
Negative power is already handled by PBTH. So not sure what is going wrong with your virtual device.
