### ISSUE TITLE
Issue when Price is negative

### ISSUE THREAD

**Issue by fafrits** [gruijter/com.gruijter.powerhour#128]
I used And Card "The Price is one of the (X) number lowest in the period be fore (x) time o'clock to start dishwasher and washing machine during low rate hours. Works great except when rates are negative. Then machines do not start at lowest rate but directly when price becomes negative. It is not a big issue but I think it should be better.

**Comment by TheMoen** [comment]
I had exactly the same issue. Today it is 12 hours with negative prices. resulting in true result all those 12 hours.
Result of my debugging is visible here:
![image](https://github.com/gruijter/com.gruijter.powerhour/assets/116985865/7262901e-aab9-414c-b15c-19ff36e3a9ea)

**Comment by stefan-schweiger** [comment]
I think this should be fixed by this PR https://github.com/gruijter/com.gruijter.powerhour/pull/154
