### ISSUE TITLE
Add support for Cyprus

### ISSUE THREAD

**Issue by thomaswitt** [gruijter/com.gruijter.powerhour#129]
`PBTH now also supports Spot Pricing (Day-Ahead 1 hour pricing) for energy providers from all EU countries`

… which is not correct, Cyprus is not supported. Any chance for support?

**Comment by gruijter** [comment]
I would love to add Cyprus. But the official data source never has any data for Cyprus: https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show

You could contact them and ask why Cyprus data is missing.
