### ISSUE TITLE
Smart power plug not recognised

### ISSUE THREAD

**Issue by Tor-Aksel** [gruijter/com.gruijter.powerhour#13]
My Apex Smart Plug (EVA smart plug) is not found by the power by the hour app for Homey Pro, but my EVA smart power reader (han) is.

**Comment by gruijter** [comment]
PBTH needs `meter_power` as capability. Please contact the dev of the EVA app to find out what capability he/she is using, and if he/she is willing to change it to the `meter_power` default.

**Comment by Tor-Aksel** [comment]
Hi,
I have for the last weeks been in dialog with them around this issue. After investigating their software, for a few days a go they came back to me saying that they because of their hardware design can’t change their software. I can not verify if this is correct or not. Only have to wait until a solution arrives one day in the future.
Thank you for following up my question to you.

Best regards
Tor-Aksel Froyland

Sendt fra min iPad

**Comment by gruijter** [comment]
have they published their source code somewhere? I could take a look at it.

**Comment by Tor-Aksel** [comment]
Thank you, I will talk to them and ask about their source code. Will come back to you. 

Sendt fra min iPhone

**Comment by Tor-Aksel** [comment]
Hi,
I just wanted to say thank you for all new versions, with new functionality and support also for the Apex Eva smart plug.

i love have this app now performs.

Best regards
Tor-Aksel Froyland

**Comment by gruijter** [comment]
Thx for your nice feedback 🤗

Glad you find the app useful!

**Comment by Tor-Aksel** [comment]
God afternoon,
After updating the new version of Homey, two of my eleven «Power by the hour» devices lost their historie Power data. They Are still receiving new data but the historic data Are lost. I have made a diagnostikk report for you to look at if you have time. The report is named 35904638-31bd-4eab-bfc9-80fc90cfd270

Best regards
Tor-Aksel Froyland

Sendt fra min iPad

**Comment by gruijter** [comment]
Hi Tor-Aksel,

The historic reporting was changed around November last year. It is caused by changing the capabilities so they can be shown on the device tile. The data is no lost, it is stored in the same device under a different name.

See related topic here: https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/411

**Comment by gruijter** [comment]
So I guess you are on the experimental firmware. Is this the fw that got installed?

`Homey v7.3.0-rc.6`

**Comment by Tor-Aksel** [comment]
Yes

Sendt fra min iPad

**Comment by Tor-Aksel** [comment]
Hi,
After installing two new versions of the Homey firmware/software, I have noticed that all my installed instances of your app have lost its connection to the «mother/parent» device. Haven’t found any way to reconnect then so I ended up removing and reinstalling. I also noticed that this situation is not caused by the installation but the restart of Homey. I therefor Ask a question if it is possible to integrate a new parameter in the configuration setting where one can register to use an external flow also for adding Power consumption? In case you decide to integrate such a function, we would also need some enhanced function in the flow.
i hope you understand that I only want the best for your already fantastic app.



Best regards
Tor-Aksel Froyland
Sendt fra min iPad

**Comment by Tor-Aksel** [comment]
﻿Hi and god afternoon,
Thank you for taking the time to answer me.
I meant versions RC7 and RC6, and «Yes» I waited from minimum 2 hours and up to several days. After installation of the RC7 several of the instances have still not reconnected. May be this has to do with the RC7 experimental version, and if this is the case I can wait for the final version. No stress for me, but if that doesn’t help what options do I have to reconnect what seems as broken connections? 
What I was writing in my last Email was just meant as a suggestion, since the other apps I am using is having Power update via flows and these apps didn’t lose connection After this installation restart. may be I am using/doing somethings wrong but I assumed this could be a way forward if a link to the mother device is broken. Sorry if this is confusing to you, only mean to participate and help.

i am using many APEX EVA 16A smart plugs, which only can deliver Power output, but on the HAN device on my Power meter, I use energy. This instance of your app also lost its link to the mother device After last RC7 restart.

The Power plugs I use (Aqara, Apex Eva, Popp) have a when flow card saying «when Power consumption changed», and other apps I use have a then flow card saying « update the Power/enery from ..» and a input parameter I can link to the smart plug. To me this seems like a lighter connection since there Are no direct connection open when Homey restart, but excuse me if my assumption is wrong.
.
Tor-Aksel

**Comment by gruijter** [comment]
Hi Tor-Aksel,
No worries, I appreciate your input. It is just difficult for me to reproduce the issue because the app now has so many ways of using it that I have to make sure how you are exactly using it before I can search for the core issue. Guess that is the downside of trying to make an app that accommodates everybody. Also your screenshots were not coming through here, and screenshots usually help me a lot trying to figure out what people mean when describing something.

So as I now understand the problem is when using a source device via its power (watts). When you pair it it runs ok. But when Homey reboots it does not. 
I just tried to reproduce this on my own Homey. The PBTH device does start up eventually, but it is not updated anymore. Is that also what you are experiencing?

**Comment by Tor-Aksel** [comment]
Hi again,
Yes, exaktly how it behaves For me also. Initialy I believed it had to do with the software update, but after restarting several times I now think it has to do with the close connection between mother device and your app. As you said, it runs very nicly as long as Homey is not restarted. I agree totally, but Homey users may from time to time have a need for restarting the Homey. 

i tried to send you two screen shot but got a long error Mail back.

Tor-Aksel


Sendt fra min iPad

**Comment by gruijter** [comment]
That was a tough one. But I think I cracked it. Can you try this new version?

https://homey.app/a/com.gruijter.powerhour/test/

**Comment by Tor-Aksel** [comment]
Hi,
Will download now and start testing

Sendt fra min iPad

**Comment by Tor-Aksel** [comment]
Good morning,
I have now restartet my Homey two times and The links between The mother device and your app survived both times. Fantastic and thank you, well done. 

Tor-Aksel

Sendt fra min iPhone

**Comment by gruijter** [comment]
Super 🎉

I had to do special debug tricks, because it only happened during a Homey reboot. And during a reboot I am blind when it comes to debugging. And secondly I suspect the root cause to be within the Homey firmware itself, but was not able to prove that. Anyhow, I found a workaround that works. Thx 4 reporting!

**Comment by Tor-Aksel** [comment]
Hi,
After sending the privious email, I have again restarted Homey two times, with same result. Looks rock solid to me. Thanks a lot for taking the time to solve this.

i have also now etablised two virtual devices from your app. Love them.

All the best.

Tor-Aksel

Sendt fra min iPad

**Comment by Tor-Aksel** [comment]
Hi Robin,
Sorry to bother you, but I wonder if your virtual divices can be used to give total consumption from multiple physical devices? I have two heat pumps and various other heaters that I would like to see the total consuptions.

Best regards
Tor-Aksel Froyland

Sendt fra min iPad

**Comment by gruijter** [comment]
You can combine devices using the GROUP app. Then you can add the group device to PBTH. I use it myself to add two different solar panel systems.
