### ISSUE TITLE
Active tariff is not updating 

### ISSUE THREAD

**Issue by AlexanderSimin** [gruijter/com.gruijter.powerhour#130]
Hey, I cannot update the active tariff info (trying to couple it to Tibber price ), but it remains constant. Any suggestions?

Thank you,

**Comment by gruijter** [comment]
Better to use the DAP driver in PBTH.

**Comment by AlexanderSimin** [comment]
Hi,

Still cannot make it working, see attached screenshot - that is the flow,
but active price doesn't change...

What am I doing wrong?

Br, Alexander Simin

**Comment by gruijter** [comment]
I see no screenshot.

**Comment by AlexanderSimin** [comment]
The screenshot with the used flow attached - it doesn't change the active tariff
![Screenshot_2023-07-09-09-28-47-06_4bbfc4a7dd885a2bb189f300112a7ed4](https://github.com/gruijter/com.gruijter.powerhour/assets/138973622/2534adca-888a-42fc-944a-2861eded6ed7)

**Comment by gruijter** [comment]
This is not how to use active tariff. This looks like a support question, not an issue with PBTH. Better go to the forum for support how to use dynamic tariff with PBTH.
https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535

**Comment by gruijter** [comment]
Closing
