### ISSUE TITLE
Wrong hourly price during summer time in Sweden

### ISSUE THREAD

**Issue by Allectra** [gruijter/com.gruijter.powerhour#132]
Shows the wrong price when we have summer time in Sweden

**Comment by gruijter** [comment]
Are you sure about that? PBTH handles timezones and DST. Is Homey itself in the correct time zone?

**Comment by Allectra** [comment]
It has corrected itself. All prices are now correct and updated.

---

2023-07-25 23:37 skrev gruijter:

> Are you sure about that? PBTH handles timezones and DST. Is Homey 
> itself in the correct time zone?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/gruijter/com.gruijter.powerhour/issues/132#issuecomment-1650596043
[2]
