### ISSUE TITLE
Export with Google Sheets > Wrong number exported

### ISSUE THREAD

**Issue by neoscaler** [gruijter/com.gruijter.powerhour#134]
I try to export the previous month & year kWh to Google Sheets with the Google Sheets app. It works, but strangely the exported number is off one digit.

In Power By The Hour I see:
78.0166 kWh

In Google Sheet gets exported:
780.166

Is this a bug in this app or in the Google Sheets app from Athom?

**Comment by gruijter** [comment]
Google sheets probably has a different decimal / thousands delimeter set (. In stead of , or vice versa)

**Comment by neoscaler** [comment]
Good idea. I just created a variable and set it via flow from the tag PBTH creates.

And it is the correct number, with a dot as divider. So it's no bug here, we can close this issue.

**Comment by neoscaler** [comment]
For the record: It was definitely the locale, thanks for the hint. Created a new Sheet with US local and the export works as expected.
