### ISSUE TITLE
Some days ago, negative kWh appeared one after another

### ISSUE THREAD

**Issue by xgbcman** [gruijter/com.gruijter.powerhour#135]
I have som PBTH devices counting from house meter, radiators, washing machine and tumble dryer. Some days ago a negative value on this day appeared (starus indicator on device). I knew the correct value and made a change in settings. Next day the same happened with another PBTH and today with two more.
The readings on the source devices are correct.
No other changes in devices.
I can find negative "power" in Insights on PBTH devices when problem occurred. When I correct value in settings for PBTH device the negative "power" is zeroed.
Diagnostics report: 9ead91e1-3311-4376-b03f-6e3bbb81fca2

**Comment by gruijter** [comment]
If you still have an issue, please reopen

**Comment by xgbcman** [comment]
> If you still have an issue, please reopen
One PTBH device had the same issue some days ago. It was solved when I restarted the PTBH app.
I have now a work-around: Restart the app at every morning.
