### ISSUE TITLE
New IF-Card proposal...

### ISSUE THREAD

**Issue by Riksona7** [gruijter/com.gruijter.powerhour#137]
What I miss is an IF-Card ( or AND-Card ) with "De prijs is een van de ... laagste in de komende bekende uren **voor ... uur**" !

This would make it possible to load the battery of my car starting somewhere in the afternoon (>13:00) and have it at 100% de next morning let say at 08:00... The available cards have a scope of TODAY ( ignoring possible low hours between midnight and 08:00 ) or MAX-12 HOURS BEFORE 08:00 ( ignoring low hours between 13:00 and 20:00 ) or ALL KNOWN HOURS ( focus on low-prices of tomorrow afternoon, leaving my battery half filled at 08:00 )...   

With this new card it would be possible to have a "all known hours" scope but before a set time ( in my case 08:00 )

**Comment by bsmout** [comment]
I agree, that's something I'm missing as well.

**Comment by gruijter** [comment]
Can you please post it here: https://community.homey.app/t/app-pro-power-by-the-hour-feature-requests/69740

you can link to this github issue in the text.

**Comment by gruijter** [comment]
I extended the selectable hours. If you still need something else please post the request here:
https://community.homey.app/t/app-pro-power-by-the-hour-feature-requests/69740
