### ISSUE TITLE
Power by the hour app for Homey Pro giving negativ power consumption

### ISSUE THREAD

**Issue by Tor-Aksel** [gruijter/com.gruijter.powerhour#14]
I am using a EVA power consumption reader (HAN reader) as input source for the power by the hour app. The power consumption is constantly changing but in the power by the hour app the consumption is showed with a negativ sign every one-five minute

**Comment by gruijter** [comment]
can you check if this is still the case in the new app v3.3.1? If so, please provide more details on what is wrong (e.g. with screenshots)

**Comment by Tor-Aksel** [comment]
Hi,
Thank you for answering me. It seems to be working now.

Best regards
Tor-Aksel Froyland 

Sendt fra min iPad

**Comment by gruijter** [comment]
Super! Thx 4 reporting the issue.
