### ISSUE TITLE
Time synchronization

### ISSUE THREAD

**Issue by hrikken** [gruijter/com.gruijter.powerhour#140]
I have a question about the time synchronization. I have a dynamic energy contract and I've noticed that the actual price is running 1 hour late compared to the pricing of my energy provider. The pricing itself is ok but the time stamps are not. How do I handle this issue? What is the cause?

**Comment by gruijter** [comment]
Is your Homey in the correct timezone and DST setting?

**Comment by hrikken** [comment]
Seems correct: 
![image](https://github.com/gruijter/com.gruijter.powerhour/assets/44940120/aeeb10f8-782e-41e0-8f85-6129a5a6968d)

**Comment by hrikken** [comment]
Don't know where / how to change DST...

**Comment by gruijter** [comment]
And when you say timestamp, do you mean the timestamp in the app logs? Or do you mean in Insights?

**Comment by hrikken** [comment]
I looked at it more closely and it seems that **the problem is in the time the trigger coming from the flow**. This is actually **one hour late** but maybe I misinterpret the trigger conditions because I'm a newbie to Homey. 
Simply put: I want to trigger an actuator (switch or whatever) as soon as the price is on its lowest for the current day but this trigger comes 1 hour late.
In de picture you'll see the visuals of 4 data providers:
- ENTSO-E: an EU market price datahub
- ANWB: my energy provider
- The Grafana data (timestamps are UTC!!)
- The insights
It looks allright to me.
![image](https://github.com/gruijter/com.gruijter.powerhour/assets/44940120/449f4060-3594-4fee-bef7-35713101326f)

**Comment by hrikken** [comment]
An example of what I intend to accomplish: I switch on my dishwasher as soon as the price is on its lowest today.
![image](https://github.com/gruijter/com.gruijter.powerhour/assets/44940120/4f1fbb03-c90c-42f7-9636-690218051c4c)

**Comment by hrikken** [comment]
My Homey: 
![image](https://github.com/gruijter/com.gruijter.powerhour/assets/44940120/2447f208-7c15-42f8-a863-587b70139000)
![image](https://github.com/gruijter/com.gruijter.powerhour/assets/44940120/93f50652-f0bf-4e3e-a264-357659e9e9ce)

**Comment by gruijter** [comment]
I cannot reproduce your issue. Triggers are on time for me. Are you sure the trigger is an hour too late?

**Comment by PeterKawa** [comment]
Keep in mind the insights graphs use UTC time at Homey Pro 2023. It's a bug.
![Screenshot from 2023-10-30 17-04-42](https://github.com/gruijter/com.gruijter.powerhour/assets/74005072/26719f7c-ad9b-44d5-89f1-fb5a9dd455fa)
