### ISSUE TITLE
Question monthly price 

### ISSUE THREAD

**Issue by lovegren22** [gruijter/com.gruijter.powerhour#141]
Hi.

Please close this ticket if this already have been asked.

Many people in Sweden uses a monthly tariff based on the daily average price each day. 

I am wondering if its possible to create a device for the monthly average price, see example below. Its in Swedish but this updates every day and makes you create a figure how much the month will cost.  

https://www.vattenfall.se/elavtal/elpriser/rorligt-elpris/

**Comment by gruijter** [comment]
Not sure what monthly price has to do with day-ahead pricing. Anyhow, you can already create Insights graph using the average price of this day.
![2023-08-21](https://github.com/gruijter/com.gruijter.powerhour/assets/19174120/8374a01c-5a5f-4c3c-9e07-d8e5d4cdcd8f)

If you want to discuss the use case of your feature request, please post it here: https://community.homey.app/t/app-pro-power-by-the-hour-feature-requests/69740

I will close the GitHub issue.
