### ISSUE TITLE
Love to have

### ISSUE THREAD

**Issue by Laszlo1707** [gruijter/com.gruijter.powerhour#143]
A possibility to daily update variables in HP23 pro with lowest spot price for electricity for tomorrow night and daytime. It would be valuable for deciding wether use  solar or nett power. You already have a card that provides a string for spot prices for tomorrow. I don’t understand how to automatically pick the lowest prices for night and day. A hint would be very appreciated. 
best regards
Laszlo Centerham

**Comment by gruijter** [comment]
Hi Laszlo. The lowest/highest price for today and tomorrow is already available as tag in flows. I will not distinguish between day and night. But there are plenty flows available that can do that. E.g. `lowest price in the 12 hours before 18 oclock`
