### ISSUE TITLE
Current price is not updating..

### ISSUE THREAD

**Issue by erikdalera** [gruijter/com.gruijter.powerhour#145]
Hi, After the newly update 5.7.3 or 5.7.4 my devices dosent update current price automaticlly, tried to recreate device and reinstall same issue.

**Comment by gruijter** [comment]
probably temporary outage of the source data. My NL prices are working fine.

**Comment by erikdalera** [comment]
Nah all of my diffrent prices dident update.. But when i upgrade my homey
to 10.0.1 it started working again!

Den fre 22 sep. 2023 10:42gruijter ***@***.***> skrev:
