### ISSUE TITLE
No flowcards

### ISSUE THREAD

**Issue by tjarb** [gruijter/com.gruijter.powerhour#146]
Hi, I have  5.7.4 installed on homey 2023 pro but there are no flow cards available. NONE!
Also the app is not visible in the flows app-lists, not in the simple flow composer and not in the advanced flow composer.

**Comment by gruijter** [comment]
Weird. I have all flowcards still there. Are you on latest stable Homey firmware (v10.x)?
And/or try rebooting your Homey.

**Comment by tjarb** [comment]
I have auto update enabled so I would expect to have the latest version.


Op zo 24 sep. 2023 14:59 schreef gruijter ***@***.***>:

**Comment by gruijter** [comment]
You do have a device added?
Did you try restarting Homey?

**Comment by tjarb** [comment]
Restart of homey, i'm not sure I've tried that. I think so.
I moved to Frank app for energy prices.

Best regards

Op za 18 nov. 2023 21:39 schreef gruijter ***@***.***>:
