### ISSUE TITLE
Can't get FlowCards to work

### ISSUE THREAD

**Issue by fhmattsson** [gruijter/com.gruijter.powerhour#149]
When testing the flow cards, I can't get it to work.

<img width="403" alt="image" src="https://github.com/gruijter/com.gruijter.powerhour/assets/43251375/a4c0bd5e-2eed-4ded-89ab-085c31cae1ab">

<img width="434" alt="image" src="https://github.com/gruijter/com.gruijter.powerhour/assets/43251375/93c06145-18b6-4f15-a011-a189a46f8a1c">

This card evaluates to True, when it really should be False

The card uses "When is price is greater than"

**Comment by PeterKawa** [comment]
Try this flow
![Screenshot from 2023-10-30 16-44-14](https://github.com/gruijter/com.gruijter.powerhour/assets/74005072/f656f416-c3fd-4975-bace-98d8b642c773)

The price tag is a local tag:
![Screenshot from 2023-10-30 16-44-28](https://github.com/gruijter/com.gruijter.powerhour/assets/74005072/1c4f6668-f9ad-40dc-b482-25b8e94bf2c4)
