### ISSUE TITLE
Not supported

### ISSUE THREAD

**Issue by follox** [gruijter/com.gruijter.powerhour#15]
Hi,

I have had some help making a integration to Homey from StecaGrid Coolcept inverters via Better Logic, HTTP request flow cards and https://homey.app/en-us/app/com.arjankranenburg.virtual/Virtual-Devices/.

It works like this:
Measure_power is a property from a device that accepts Watts as value. Its a virtual device rather than a Solar panel app.
In short the HTTP get JSONpath does the XML grab. the string goes to the tree xml and grabs array number [2] which is your watt value and inserts that in to variable in Better Logic.
Then the flow at when variable changed (better logic) it will update the measure_power attribute of steca 1 or 2 to that number 

However, I am not able to get Power By The Hour to find the buttons. 
![image](https://user-images.githubusercontent.com/43533933/151124856-40a440b3-2327-4e1f-9373-7af8f1365a9a.png)

**Comment by gruijter** [comment]
measure_power devices should now work in version 4.0.1.

**Comment by follox** [comment]
Awesome, I will try it out immediately. Would you like me to report back if it is working fine or not?

**Comment by gruijter** [comment]
yes please :)
