### ISSUE TITLE
Ability to choose capability or repair device to choose capability for given device + setting energy flow direction

### ISSUE THREAD

**Issue by shaarkys** [gruijter/com.gruijter.powerhour#150]
Hi [@Gruijter](https://community.homey.app/u/gruijter) , 

I wonder if it’s possible to track energy I’m getting from grid and sending to grid. For this case, it’s inverter device, which has following capabilities : capabilities":[“measure_solar_power”,“measure_load”,“measure_feed_in”,“measure_battery_power”,“measure_battery_soc”,“measure_solar_dc_1”,“measure_solar_dc_2”,“status_inverter_use_mode”,“status_inverter_run_mode”,“measure_export_limit”,“measure_generation_today”,“measure_temperature_battery”,“measure_temperature_inverter”,“measure_power”,“measure_battery”,“measure_battery_power_today_max_in”,“measure_battery_power_today_max_out”,“measure_feed_in_today_max_in”,“measure_feed_in_today_max_out”,“measure_load_today_max”,"measure_solar_power_today_max

I can probably make virtual device / DC device, which will populate measure_feed_in as measure_power and then add it as Power by the hour device ? **I’m trying to replicate this but seems PBTH is not picking up such device… ?**

I just wonder, wouldn’t it be possible simply to select capability when pairing/creating and/or maintenance device and the flow direction (eg. negative for getting power from grid and positive when exporting grid - so both can be tracked) ? That would simplify such requirement (tracking exported energy, tracking imported energy and associated costs)

Thank you.

Submitted also on forum : https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/1794

**Comment by gruijter** [comment]
I added it to the wish list, but don't hold your breath for it ;)
https://community.homey.app/t/app-pro-power-by-the-hour-feature-requests/69740/152
