### ISSUE TITLE
Missing 4 o'clock in the morning

### ISSUE THREAD

**Issue by KentTage** [gruijter/com.gruijter.powerhour#153]
Hi!

I have set up an advanced flow that is triggered every hour (on the hour) with a 10 s delay. (When I ran the When card on the hour it seemed to not have updated to the new price yet.) I then check with a When flow-card "The price is one of 6 lowest in the 12 hours before 7 o'clock". I'm not entirely sure this is supposed to work since it requires that you keep yesterday's prices in addition to the next day's prices, but it is when my car is parked and when the price is usually the lowest, so I'm hoping that it should be possible.
I trigger activation of my car charger if it is one of the lowest priced hours and if it is not, I turn off the charger.
I have tested this, and it seems to normally trigger charging on the "correct" hours with a few incorrect decisions from time to time, but that could perhaps be due to changes in the exchange rate.

I have one problem and two questions with this:
* The problem is that for some reason 4 o'clock is NEVER reported. all other hours of the day are reported, but not 4 in the morning for some reason. Is this a known problem? I.e. the trigger runs, but the when-card doesn't return either of TRUE/FALSE or Error.
* For me it would be convenient if it had been possible to set this check to the following instead, but there is a 12 h cap on the card. Is it possible to fix it? - "The price is one of 6 lowest in the 14 hours before 7 o'clock". I usually get home at around 5 p.m. and if those two hours are among the cheapest, I don't see why I shouldn't use them. So, it would be convenient to be able to extend it by at least another two hours.
* Would it perhaps be smart to set up an extra device that doesn't use an exchange rate to avoid picking the wrong hours due to this, even though it would mean that I cannot use that device to understand what the current price is in my currency?

**Comment by KentTage** [comment]
A screenshot of my flow:
![Charging](https://github.com/gruijter/com.gruijter.powerhour/assets/149939173/b158f00a-4b09-4077-89b8-93dabc901849)

**Comment by stefan-schweiger** [comment]
Maybe this is also affected by this bug https://github.com/gruijter/com.gruijter.powerhour/pull/154 at least the "with a few incorrect decisions from time to time" seems like it's related

**Comment by gruijter** [comment]
closing. please reopen if it is still an issue.
