### ISSUE TITLE
tariff is not updated in electricity meter

### ISSUE THREAD

**Issue by ypstullibus** [gruijter/com.gruijter.powerhour#157]
I added this simple workflow - but tarrif stays unchanged on default:

![Flow](https://github.com/gruijter/com.gruijter.powerhour/assets/152786364/87056a3a-be57-4c32-bd0b-750a224a3143)

(I have 2 devices - therefore 2 times update of the actualPrice)

**Comment by gruijter** [comment]
yeah, you should use Euro's everywhere. So do NOT use cents in DAP, and Euro in the summarizer.
