### ISSUE TITLE
Wrong day valeu

### ISSUE THREAD

**Issue by StaffordBully** [gruijter/com.gruijter.powerhour#159]
I have set it up for measure my complete installation.

But kWh of today shows the value of my house minus the solar consumption.

But that's not correct.

See screenshot 
I have used 3.7kWh and app shows 0kWh

![Screenshot_20231207_145126_Energy.jpg](https://github.com/gruijter/com.gruijter.powerhour/assets/144690805/5fd47d21-21f2-41ae-bae1-8145191cb27c)

![Screenshot_20231207_145055_Homey.jpg](https://github.com/gruijter/com.gruijter.powerhour/assets/144690805/9d6c6a7b-580e-46ff-b494-beb264d40282)

**Comment by gruijter** [comment]
'kWh of today shows the value of my house minus the solar consumption'

That is by design. If you import the same amount that you export, your net usage is 0.
