### ISSUE TITLE
Since update invalid length

### ISSUE THREAD

**Issue by labarten** [gruijter/com.gruijter.powerhour#166]
Since update 5.9.1 invalid length issue 

“distribution has invalid length“

only for the electric kWh no issues with the gas measurements. 

it pulls the data via a homewizard P1, no issues with that device

**Comment by jboas76** [comment]
I got the same problem with reading from the meter.
![image](https://github.com/gruijter/com.gruijter.powerhour/assets/53059180/af3262f6-0793-4399-9116-4e280ee30fd8)

**Comment by gruijter** [comment]
Try changing the distribution scheme to something else, and then back to 'disable'

**Comment by labarten** [comment]
Tried without succes, I installed your test app what fixes the issue, I tried to install the official app again but then the error comes back again. So I'm now running on the test app.

**Comment by gruijter** [comment]
weird. but solved then ;)
