### ISSUE TITLE
Problem receiving data from Qubino

### ISSUE THREAD

**Issue by oddinge73** [gruijter/com.gruijter.powerhour#17]
Hello.
I have problems receiving data from Qubino smart meter, ZMNHTD1. Are Power by Hour configured to recieve data from that device?

Odd Inge Jacobsen

**Comment by gruijter** [comment]
Yes it is, but not optimally. Ser this link in the forum. If you can provide me names of the homey capabilities this driver is using (meter_power or similar)  I can make a better integration.

https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/480?u=gruijter

**Comment by oddinge73** [comment]
That worked. But where do I find names of the homey capabilities?

**Comment by oddinge73** [comment]
![Skjermbilde 2022–02–10 kl  00 21 51](https://user-images.githubusercontent.com/83422068/153307377-efe4f28a-7746-454c-9d87-5569184fe386.png)

Does this help? Screenshot from Komfyr_Σpower, renamed from Virtual_ device

**Comment by gruijter** [comment]
Sorry, no. I guess I have to create a special diagnostics function in PBTH for this.

Anyhoo, you are good to go with the watts function for now.😎
