### ISSUE TITLE
Actual gas prices (TTF)

### ISSUE THREAD

**Issue by LecramRed** [gruijter/com.gruijter.powerhour#19]
Not really an issue, but a 'great to have'. I love this app and it will help me a lot to save money.

Is it possible to automatically update the actual gas price in the app? If it knows the gas price (TTF), it is easy to calculate the cheapest energy. If the kwh price is lower than the gasprice/9.77, electricity is cheaper, so my boiler can get heated with an electrical heater in stead of gas.
I guess that if the actual hour kwh price can get updated automaticallly, the gas price update is no rocket science, isn't it?
https://www.powernext.com/spot-market-data

**Comment by gruijter** [comment]
I'd love to add gas prices. But what prices are the right ones? There is a link to a .csv file. Does that contain the correct price?

https://www.powernext.com/sites/default/files/download_center_files/NGP-Current-Prices.csv

And if so, does it not depend on where in Europe you are? And how would you calculate your own markups?

**Comment by LecramRed** [comment]
I think that this is the right price. The price is more or less dynamic, but within a day, there is not a big difference between the hours. 
At least the Netherlands is using TTF prices for gas, I am not en expert, so I don't know if the TTF prices are also used in other european countries.

**Comment by gruijter** [comment]
Im utterly confused. 😵‍💫

What is TTF vs CEGH VTP vs CEGH VTP_WD vs  CZ VTP vs ETF vs THE vs PEG vs ZTP vs PVB? What do the abbreviations mean?

And what is the difference between End of Day, European Gas Spot Index, Within Day and Neutral Gas Price?

And how do you know which reference price your energy provider is charging?

**Comment by LecramRed** [comment]
According the Gasunie website is TTF the only way to trade natural gas in the Netherlands: https://www.gasunie.nl/gasinfrastructuur/title-transfer-facility-ttf
It also says that TTF is leading in Europe: Er wordt zo veel gas op TTF verhandeld, dat de gasprijzen op het platform maatgevend zijn voor Europa. Ook in de rest van de wereld kijken ze goed naar wat er op TTF gebeurt.
Energy provide Nieuwe Stroom explains this on its website: https://www.nieuwestroom.nl/energiemarkt/energiebeurzen/gas-handelsbeurs/
They call it LEBA day ahead. It is confusing to see that different gas suppliers have (slightly) different rates.

**Comment by gruijter** [comment]
Ah that explains part of it to me. But would TTF be the base price for all EU consumer energy suppliers? And how is transport cost calculated?

EasyEnergy has a weblink to EPEX for pricing: https://www.epexspot.com/en/market-data?market_area=NL&trading_date=2020-04-21&delivery_date=2020-04-22&underlying_year=&modality=Auction&sub_modality=DayAhead&product=60&data_mode=table&period=

But there you can select a EU region. So  that suggests pricing varies per country (which would make sense to me somwhow)

**Comment by gruijter** [comment]
especially for you:

https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/557

Can you please test and let me know?

**Comment by gruijter** [comment]
Any feedback?
Here is a link to the latest version: https://homey.app/a/com.gruijter.powerhour/test/
