### ISSUE TITLE
Power by the hour does not recognize INNR outdoor smart Plug

### ISSUE THREAD

**Issue by Platvoetje** [gruijter/com.gruijter.powerhour#191]
Hello
In the power by the hour app in homey it does not recognize the INNR outdoor smart Plug as I cannot select it.
Is this normal and can this be added.

with kind regards
Friso Rauwerda

**Comment by gruijter** [comment]
Ask the developer to add `meter_power` as cumulative energy meter. Or alternatively find out what the capability for cumulative energy (total kWh) is named so I can add it in a next PBTH release.

**Comment by Platvoetje** [comment]
Contacted developer they will not change anything so you can close this request
