### ISSUE TITLE
App disappears

### ISSUE THREAD

**Issue by Dome0068** [gruijter/com.gruijter.powerhour#192]
Hello,
After Homey v10.2.1 installed, 1 time a day the Power by the Hour APP disappears from installed Apps and all related devices doesn't work.
I need every time to reinstall it from App Store.
Please help and let me know

**Comment by gruijter** [comment]
Do you have a HP2016/2019? And did you add a Battery Summerizer? Then make sure to disable the advanved ROI function! This only works on HP2023.

**Comment by Dome0068** [comment]
Hi,
I have an HPE2023.. Please could you explain me better which is the ROI function to disable.
Thank you for your help

**Comment by gruijter** [comment]
If you have HP2023 there is no issue with Battery ROI. You can try sending an app diagnostics report. Maybe I see something there.

**Comment by Dome0068** [comment]
Ok,
I have just produced a diagnostic report with ID: 892338a8-3fd6-4f78-8429-4a752984bfa1 but I would to let you know that after app reinstallation the issue is no more present at moment
