### ISSUE TITLE
HomeWizard Wi-Fi Energie Monitor 

### ISSUE THREAD

**Issue by BertWi** [gruijter/com.gruijter.powerhour#2]
Hi Rob,

a quick question: does this Homey App work for the HomeWizard Wi-Fi Energie Monitor and associated App?

Best regards,
Bert

**Comment by gruijter** [comment]
Dunno. It might. PowerByTheHour supports all devices that have meter_power capability.

**Comment by gruijter** [comment]
I looked at the source code of Homewizard energy monitor, and right now it doesnt work. I contacted Jeroen Tebbens and he will look at it while he is rewriting the app.

**Comment by BertWi** [comment]
Owh. That would be great if you guys could get it to work!
