### ISSUE TITLE
Extremely high maximum effect

### ISSUE THREAD

**Issue by TheodorStorm** [gruijter/com.gruijter.powerhour#21]
When using Power By The Hour to keep track of charge costs for an EV I have noticed that maximum effect sometimes get an extremely high value when charging is activated and then quickly deactivated again, that is goes from 0 watts to several thousands of watts (actual effect) from one minute to the other and then back to 0. Just now I got a reading of >80.000 watts in max effect according to Power By The Hour. Actual effect was around 2.000 watts for a brief moment.

Been looking at the source code a bit and it seems to stem from the way measurePowerAvg is calculated, which then wattMax is set to.

The calculation error also leads to a too high power cost being calculated.

**Comment by gruijter** [comment]
'The calculation error also leads to a too high power cost being calculated.'

If you use kWh as source the cost is based on that, not on the watt. So that should not be an issue.

Or are you using watts as source?

**Comment by TheodorStorm** [comment]
You're right, it uses kWh as source. The kWh reading is probably a problem with the Tesla Homey app, looking at the insights graph the Tesla app only seems to update kWh every few days which explains the calculated cost. 

It's just the max charge power (W) that PBTH gets wrong.

**Comment by gruijter** [comment]
If the kWh is only updated every few days, then that would explain the extreme high Watt in PBTH.I have no way to track a change in kWh over multiple days. So PBTH assumes the kWh change is happening since last midnight.

**Comment by TheodorStorm** [comment]
I see. In that case, I think this issue can be closed.
