### ISSUE TITLE
Make Advanced Flows based on price/kWh

### ISSUE THREAD

**Issue by AndersSoderqvist** [gruijter/com.gruijter.powerhour#211]
Would it be possible to implement the possibility to trigger flows based on a spot price? Want to set the temperature in my jacuzzi to different temperatures depending on if the average spot price for the next 8h are higher or lower than a specific value (price). 

Hope it is possible to give us some flow cards with price values to use.

Thanks

**Comment by gruijter** [comment]
All the price values you need are already available as tags. To use them in a flow just pick any logic card.

**Comment by AndersSoderqvist** [comment]
Awesome, thank you!👌🏻
Sent from my iPhone

28 jan. 2024 kl. 20:52 skrev gruijter ***@***.***>:

﻿

All the price values you need are already available as tags. To use them in a flow just pick any logic card.
