### ISSUE TITLE
X lowest the next x hours (homey) 

### ISSUE THREAD

**Issue by RohnnyS** [gruijter/com.gruijter.powerhour#212]
8 lowest price the next 8 hours before 05
This work perfect up to 8h.  Start to charge at 2100

But when the car need more than 8 hour it do not start. 
Lets say i need 11h to start it should start at 1800, IT does not. 
8 lowest price the next 11 hours before 05

Looks like it work upto 8 hour only. Is it possible to make this work as i think.

SUPERB APP BTW😁

Regards Rohnny S.

**Comment by gruijter** [comment]
Lets say i need 11h to start it should start at 1800, IT does not.
8 lowest price the next 11 hours before 05

If you need 11 hours to charge before 5AM, the card should be: `Is one of 11 lowest in the (20?) hours before 5`.
