### ISSUE TITLE
BTW(VAT) is not added to prices when using TTF_EOD

### ISSUE THREAD

**Issue by Platvoetje** [gruijter/com.gruijter.powerhour#217]
When using the gasprices TTF_EOD you can enter a percentage of BTW(VAT) but this is not added to the overal price.

![image](https://github.com/gruijter/com.gruijter.powerhour/assets/140010634/57c59060-2308-4db9-8c44-e915cbc6fc51)
This is without BTW(VAT)
And when you add BTW (VAT) the price will not change

**Comment by haantigoon** [comment]
I have the same problem, it seems that no VAT is charged, despite the fact that you fill in the variable surcharge

**Comment by Platvoetje** [comment]
hello when will this be resolved as this is crucial for the total price calculation

**Comment by Platvoetje** [comment]
Is this solved then in an update?

Op do 21 mrt 2024 om 11:15 schreef gruijter ***@***.***>

**Comment by gruijter** [comment]
Yes. Current version has this fixed. Did you try?
