### ISSUE TITLE
Gemiddelde prijs hoogst in periode voor tijd

### ISSUE THREAD

**Issue by MW236** [gruijter/com.gruijter.powerhour#218]
De meeste EN kaarten zijn zowel aanwezig voor als de prijs hoog is, als voor wanneer deze laag is. Dit geldt niet voor de volgende kaart:

“De gemiddelde prijs komende _komende uren_ U wordt het **LAAGST** in de _periode_ uren voor _tijd_ uur” 

Het zou mij heel erg helpen als deze ook beschikbaar hebben is voor als de gemiddelde prijs het **HOOGST** is. Bij ALS kaarten is deze overigens wel aanwezig.

**Comment by gruijter** [comment]
Added to 6.5.0. Pls test and let me know.

https://homey.app/a/com.gruijter.powerhour/test/

**Comment by MW236** [comment]
Thank you!

I made a flow with the 'de gem prijs voor de komende X uren is het hoogst van de periode'. It does what it needs to do. So for me the test was successful.
