### ISSUE TITLE
electricity meter Iungo does not work

### ISSUE THREAD

**Issue by ezwep** [gruijter/com.gruijter.powerhour#22]
I use an Iungo device to read my smart meter.  if I add these in the app, the values ​​are not read and visible.  is there anything that can be done about this?  The gas meter values ​​that also go through the Iungo are read well

**Comment by gruijter** [comment]
I checked the source code of the Iungo app. It is using non-standard capabilities. But the meter_power is available. So in the advanced device settings in PBTH switch on 'use watt as source'. That should work for you as fall back method.
