### ISSUE TITLE
BTW in de Gas Summarizer lijkt niet meegenomen te worden vanuit TTF_EOD.

### ISSUE THREAD

**Issue by haantigoon** [gruijter/com.gruijter.powerhour#220]
Het lijkt erop dat het bedrag uit TTF_EOD (Day-Ahead Gas Prijzen) zonder BTW wordt doorgezet naar de Gas Summarizer.

**Comment by haantigoon** [comment]
![Gasprijs berekening](https://github.com/gruijter/com.gruijter.powerhour/assets/137299945/7804e3e3-46cc-4d15-95cd-f11986e3a8ef)

Ik weet even niet wat er mis gaat, maar verschil in prijs tussen wat ik bereken en wat er in Pbth staat kan ik niet verklaren.enig idee?
Dacht in eerste instantie dat het met de BTW mis ging maar kan dat niet onderbouwen.

**Comment by gruijter** [comment]
should have been solved. If not please reopen
