### ISSUE TITLE
Electricity bar graph not updating automatically 

### ISSUE THREAD

**Issue by ReidarAOL** [gruijter/com.gruijter.powerhour#221]
The hour by hour electricity bar graph is No more automatically updated in the last version of Homey Pro 2023.
I can update them manually and the graph shows correct prices, but if I close and open it will show previous prices again.
before restarted the app yesterday it loaded 16 days old prices in the bar graph.
today it shows yesterdays prices when loaded.

**Comment by gruijter** [comment]
Nothing I can do from the app. The refresh is pushed every hour by the app.
Maybe you got a firmware update from Homey? Or a mobile app uodate?
And maybe you are not closing the mobile app properly?
Anyhoo, there is a refresh button in the mobile app. Just use that😉
