### ISSUE TITLE
Action cards to set energy summarizer pricing

### ISSUE THREAD

**Issue by oh2th** [gruijter/com.gruijter.powerhour#223]
Since the beginning of April, I have a contract where I can choose to use:
- spot price as is
- 50% fixed price / 50% spot price (have no idea how this is calculated
- 100% fixed price
This choice can be made on monthly basis in advance.

On the energy summarizer settings, would it be possible to have action cards to:
- Set the active tariff `price`.
- Set the tariff update group to `number`.

This would allow switching between fixed pricing and different update groups for the summarizer from a flow. I.e. Midnight on the first day of the month.

**Comment by gruijter** [comment]
`Set the active tariff price.` is already possible, but not for an individual device. It is done by tariff group.

`Set the tariff update group to number`. I will look if I can implement that.

**Comment by gruijter** [comment]
Should be working in 6.5.0
https://homey.app/a/com.gruijter.powerhour/test/
