### ISSUE TITLE
Prijsgrafiek

### ISSUE THREAD

**Issue by MartinvD1** [gruijter/com.gruijter.powerhour#225]
Als ik het "apparaat" open zie ik een een handige grafiek met de prijzen per uur voor die dag. 

![Screenshot_20240426-133403~2](https://github.com/gruijter/com.gruijter.powerhour/assets/57069525/b838da07-b0cb-4665-9af9-cc2e238938cf)

Als ik deze grafiek verwerk in een flow (afbeelding in een dan kaart) dan word de grafiek niet vernieuwd waardoor je continu naar dezelfde grafiek kijkt. Ben ik iets vergeten om toe te voegen in de flow?

**Comment by gruijter** [comment]
Geen idee. Vraag voor het Homey forum lijkt me.
