### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by HugoPerfors** [gruijter/com.gruijter.powerhour#226]
Dit is geen nieuw probleem. Maar wat gebeurt er precies als ik een tariefsoort instel.  Van 1. - 10
Kan ik hiermee dag en nacht tarrief instellen?

**Comment by HugoPerfors** [comment]
Dat zit in Dap-El.  Bij geavanceerd.

**Comment by gruijter** [comment]
Please read through the forum: https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535
