### ISSUE TITLE
Preis in der App weicht von dem echten Preis bei Tibber ab

### ISSUE THREAD

**Issue by timnagel-hamburg** [gruijter/com.gruijter.powerhour#228]
Hallo,

der aktuelle Preis in der App wird mit 0.1136 EUR angegeben, tatsächlich liegt aber aktuell bei Tibber bei 0,36 EUR. Wie erhalte ich in der App den richtigen Preis von Tibber?

Viele Grüße aus Hamburg
Tim

**Comment by gruijter** [comment]
please check the Homey forum for support.
You need to set local taxes and markups.
