### ISSUE TITLE
Average price not working correctly 

### ISSUE THREAD

**Issue by olandale** [gruijter/com.gruijter.powerhour#23]
The average price next hours card does not seem to be working correctly. When I set the price (NO_Norway5) to be turned on when the average price is lowest for the next 2 hours on the period of this day. Sometimes it turns on every hour. And sometimes not at all.

**Comment by gruijter** [comment]
Can you share the flow you are using, and the exact date and hours where you noticed this happening?

**Comment by gruijter** [comment]
I can confirm something is wrong with this flow card. I need to dig into the algorithm I am using. Pls have patience.

**Comment by olandale** [comment]
Love your app so far.

Mvh
Ole Andreas Dale
________________________________

**Comment by gruijter** [comment]
Should be fixed in version 4.2.8.

I have not tested it very thorough, but I am pretty sure I nailed it. Can you let me know if it now works?

**Comment by olandale** [comment]
Hi again. I'm sorry to say, but I don't think the fix have worked. I didn't get any push notification today when the prices was the lowest average of the day.

Mvh
Ole Andreas Dale
________________________________

**Comment by gruijter** [comment]
Mmh.. I created several trigger flows myself. And until now all is working as it should... I will track this for a few days and see if I can reproduce your issue.

**Comment by gruijter** [comment]
should be fixed in the new version 4.2.9

**Comment by olandale** [comment]
I think that you got it now. Great job. I will be testing it out a bit more.

Mvh
Ole Andreas Dale
________________________________

**Comment by gruijter** [comment]
Yes my own testing also works good. Ill close the issue. Thx again for reporting.

**Comment by olandale** [comment]
App diagnostic report is 05ebe0e6-5036-4c17-a366-cd7e0907f455.
Flow I'm using https://homey.app/f/uoOAC3. The date it triggered the whole day was May 14 and 15. May 13 it didn't trigger at all. After that I stopped using it and only let me send notifications.
Maybe the average price next hours card should have been used as the AND card? And the trigger card (when) could be when price change?

Mvh
Ole Andreas Dale
________________________________

**Comment by gruijter** [comment]
I somehow did notreceive your diagnostics report. But anyhow, the flow should trigger ok unless the price api (the source of price data) is down. That could explain if it didnt work for a day or so. If the price info was not updated on May 13 you should be able to see that in your Insights.

By the way, May is a long time ago already...
