### ISSUE TITLE
Power by the Hour uninstalled unexpectedly

### ISSUE THREAD

**Issue by Kopiokone** [gruijter/com.gruijter.powerhour#241]
Just noticed when I tried to go to Power by the hour app settings that it said that app did not exist. It had somehow uninstalled itself.

Was able to reinstall from the app page, which retained my flows and there wasn't any damage as such. Just that my automations did not receive current prices for last 3 hours or so.

I am certain I had not even visited the settings today so I could not have uninstalled it myself.

**Comment by gruijter** [comment]
Weird. Seems more a Homey issue.
