### ISSUE TITLE
Day-Ahead E Prices from CZ Ceps is not working.

### ISSUE THREAD

**Issue by MichalStranik** [gruijter/com.gruijter.powerhour#242]
Since 24.09.2024 app doesn´t update prices for CZ_Czech_Republic_CEPS. 
I tried to add new device, but that also doesn´t read any data.
I tried restart app, still no difference.
It may be temporary problem on CEPS side.

**Comment by gruijter** [comment]
Solved

**Comment by MichalStranik** [comment]
Thank you, it was working, but it is not anymore.
