### ISSUE TITLE
Day ahead energy price de_germany not shown

### ISSUE THREAD

**Issue by Besmart1518** [gruijter/com.gruijter.powerhour#245]
When adding de_germany as a device for day ahead energy, no values are shown. It only shows „55years ago“ as latest update. I tried with other countries, which worked well and shows prices and graphs.
![IMG_4332](https://github.com/user-attachments/assets/465147ea-ce2a-422e-be4e-c8e963f922af)

**Comment by VitaliBabkin** [comment]
EE broke down yesterday, too (

**Comment by gruijter** [comment]
Should be fixed in latest version

**Comment by VitaliBabkin** [comment]
Yes, thank you for your work
