### ISSUE TITLE
Summer to wintertime Netherlands

### ISSUE THREAD

**Issue by NCVervaet** [gruijter/com.gruijter.powerhour#254]
Hello, since the change from summer to wintertime in the Netherlands, the Day Ahead prices in my Homey Pro 2023 are incorrect. The last update is from 3am. At the moment (21h) the current price reads the price at 3am. It says the lowest price is 20 'o clock, which is lowest hour in next 8h. This can not be correct. 

I've reset the Homey pro, replaced the cards in several flows, but the prices do not get updated.
![DayAheadPrices](https://github.com/user-attachments/assets/820c9b27-6bc7-4491-8815-ad60c2fd1c58)

Anyone else with the same issues after change of summer to wintertime?

**Comment by antonhagg** [comment]
I have not got any updated of New prices. Not sure it relates. Im in Norway.

**Comment by jeroenvano** [comment]
Yep, same issue. No updates since start of winter time.

**Comment by antonhagg** [comment]
Which version are u on?

**Comment by jeroenvano** [comment]
I am on 6.6.4

**Comment by antonhagg** [comment]
Ok, looks like there is an issue with The ENTSO api. @gruijter is on the task. 🙏

**Comment by jeroenvano** [comment]
@gruijter 6.6.5 seems to have fixed the issues. 
Thank you <3

**Comment by NCVervaet** [comment]
Thasnks gruijter for fixing, I can indeed confirm the day ahead prices in your app work again. Cheers!
