### ISSUE TITLE
Prices for Norway-01 not updating since 08.06.22

### ISSUE THREAD

**Issue by engeloy** [gruijter/com.gruijter.powerhour#26]
All prices have been frozen since yesterday at 1600 CET. Tibber have also had issues fetching prices the last 24 hours but this now seems to be resolved.

**Comment by Wouter-Berman** [comment]
In my homey the prices are still updated every hour. Maybe reset the app?

**Comment by gruijter** [comment]
I am fetching the price info from a public API (ENTSO-E). They sometimes have issues publishing data for certain regions. The Homey app buffers as far into the future as possible, but when the API is down more then a day Homey cannot update the actual pricing.

The solution is to wait untill it is back up again.... If Tibber started to get the data, it wont take long for Homey to follow is my guess.

**Comment by engeloy** [comment]
> 

Thanks - as of 13:00 today the prices for PBTH are also updating again!
