### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by jtebbens** [gruijter/com.gruijter.powerhour#3]
Version 2.1.1

Hi Robin,

Nice work on the app and very useful for those that want to track their electic and gas usage.

My worry currently is the amountof memory it uses. I am on the old Homey 2016 and see this app is one of the top user. Is this something you can look at or is this due to the athom api it uses and the related privileges it needs. I will check if it will drop memory after some garbage collection (memory) by tomorrow but for me this is a concern.

![image](https://user-images.githubusercontent.com/18558267/94999213-323e5800-05b8-11eb-871f-7d1f9a721228.jpeg)

**Comment by gruijter** [comment]
I have no clue how to reduce the memory footprint. Memory is distributed in mysterious ways by Homey/NodeJS. On my Homey Pro it is a very average memory user.

![Screenshot_20201004-165245_Homey](https://user-images.githubusercontent.com/19174120/95018867-843bb800-0662-11eb-9995-805da1f48340.jpg)


 All I can do is make sure there isn't a leak, and as far as I checked there is no memory leak.

**Comment by jtebbens** [comment]
Hi,

Thanks for response. I can see it dropped a little to 18mb as of yesterday.  Normally when apps start they start at 25/30 and drop within a few hours but it didnt for me so hence asking.
I will close the issue, I understand it isnt easy which I noticed with the Homewizd apps.

Thanks,
Jeroen

**Comment by jtebbens** [comment]
Closing
