### ISSUE TITLE
Add money this hour.

### ISSUE THREAD

**Issue by CrazyHenk44** [gruijter/com.gruijter.powerhour#30]
Hi,

Since you implemented my last feature in a blink of an eye, here a new request.

For usage on the 'insight' page, could you add a 'money this hour' ? There is a 'Money last hour', but if you use that in Insights, you get an offset of one hour basically, see attached screenshot. The usage is in the top graph and the costs in the bottom one, but as it is the costs of the hour before, you have to look at the hour after it
![Opera Homey 15 38 54@2x](https://user-images.githubusercontent.com/5298235/176193999-b8bf3b6b-f753-404c-afbd-7ed9df361d15.png)
.

**Comment by gruijter** [comment]
There is a reason for that: Homey still cannot look into the future😉

Only when the present hour is fully over, you know how much the cost is.

Ill close the issue.

**Comment by CrazyHenk44** [comment]
Sure, but you can’t add current costs, like the usage for the current hour times the price?

It would also be fine if it is set after the hour is over. Homey can’t look in the future, but maybe we can rewrite the past? :)

**Comment by gruijter** [comment]
The current cost of any hour is available with a real-time value in the device tile, and is also available in flows. Logging the current cost in Insights would result in a sawtooth graph which is IMO useless for any user.

Come to think a bit more about what you mean I think you mean an ever cumulating total cost over the complete lifetime of a power device, similar to what kWh is doing. Is that indeed what you are looking for? If so / or not so, can you explain to me what the use case would be to have this available in Insights?

**Comment by CrazyHenk44** [comment]
You say that "The current cost of any hour is available with a real-time value in the device tile", but I can not find that in Insight. So I can not make a graph to compare my usage vs the costs.

Let me ask it differently, how can I get a graph with the costs per hour of the last 12 hours or so. Exactly similar to the graph 'money last hour' would make but then without the offset that graph has.

**Comment by gruijter** [comment]
You print the graph, and then shift the paper a bit....

I still do not understand your use case. You can e.g. export the data to excel and then substract an hour. But why would you want that?

Anyhow, Homey does not allow creating insights for with a time offset for devices.

**Comment by gruijter** [comment]
You print the graph, and then shift the paper a bit....

I still do not understand your use case. You can e.g. export the data to excel and then substract an hour. But why would you want that?

Anyhow, Homey does not allow creating insights for with a time offset for devices.

Edit: and for comparing cost with usage: in Homey they are both in hindsight, so are in sync.

**Comment by gruijter** [comment]
No more feedback. Can I close this issue?
