### ISSUE TITLE
Setting for the time zone

### ISSUE THREAD

**Issue by FoxTailN** [gruijter/com.gruijter.powerhour#31]
Nord Pool is publishing prices in CET/CEST time zone. I am located in Estonia (+1h difference vs CET), therefore "Price now" in the app is actually the price that will be the next hour. Would it be possible to add a setting to offset the time by user defined amount of hours?

PS! Thank you for the great app!

**Comment by NikitaSkitsko** [comment]
I did some testing and analyzed the pricing. Here are the results: 
- Homey time zone is set to "Tallinn, Estonia", time is 10.07.22 21:40 
- Power by the Hour (EE_Estonia) shows "price now" 0.3424 EUR/KWh
- Nord Pool shows the prices in CET time zone, therefore to identify the actual price I need to look at 20-21 time frame. According to NordPool price for EE and 10.07 20-21 is 322.12 EUR/MWh or 0.3221 EUR/KWh. For 21-22 price is 342.39 EUR/MWh or 0.3424 EUr/KWh

Conclusion
- PBTH shows pricing in CET time zone, not in Tallinn, Estonia (GMT+2 time zone)

It would be really useful to be able to offset the time zone and use PBTH as the source in flows.

**Comment by gruijter** [comment]
Ok thx 4 all the testing! PBTH should definitely use local timezone. I will dug into this further.

**Comment by NikitaSkitsko** [comment]
Thank you for that. 

Basically PBTH has to take NordPool price from the CET hour which is adjusted by the time zone difference. In my example time is 21:40, time difference with CET is 1 hour, therefore correct Nord Pool price is from CET 20-21 time frame.

**Comment by gruijter** [comment]
I just tested the following:
I put the location of my Homey in Talinn. So my Homey is running on EEST time.
I then created a PBTH device with pricing from `EE_Estonia`
At  EEST 13:30-13/7/22 Homey reports the current nett price as 0.4096
At the same EEST time ENTSOE reports it as 0.5499

https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=true&viewType=GRAPH&areaType=BZN&atch=false&dateTime.dateTime=13.07.2022+00:00|EET|DAY&biddingZone.values=CTY|10Y1001A1001A39I!BZN|10Y1001A1001A39I&resolution.values=PT15M&resolution.values=PT30M&resolution.values=PT60M&dateTime.timezone=EET_EEST&dateTime.timezone_input=EET+(UTC+2)+/+EEST+(UTC+3)

So I can confirm somewhere the time zone handling is off. It is really a PAIN IN THE ASS (!!!) to debug this in Homey. I already spent days in trying to get time zone handling correct. But the source data is using UTC and CET for electricity, and CET for gas pricing, my dev PC is using UTC with additional NL timezone, and Homey is using UTC and is only able to handle local time zones by performing magic....

But no worries, I'll work on this without sleep to get it fixed for any Homey user anywhere in the world

**Comment by gruijter** [comment]
Ok, found the root cause of the issue. It is the ENTSOE API who are delivering the pricing information.

It appears they normally deliver pricing info per day, where a day is adhering to the local time zone. But off course they managed to create exceptions in some markets, and Estonia is apparently an exception.

https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html#_query_response

So I had to completely rewrite the code for fetching pricing info from ENTSOE, combining data from multiple days to create price info for a local time zone day that works WITHOUT EXCEPTIONS.

I'm testing now and will release a test version for you later.

**Comment by gruijter** [comment]
Test version 4.4.3 here: https://homey.app/a/com.gruijter.powerhour/test

Let me know if this fixes your problem @FoxTailN

**Comment by gruijter** [comment]
Super!
