### ISSUE TITLE
Feature request: fixed markup changes during day/night

### ISSUE THREAD

**Issue by gruijter** [gruijter/com.gruijter.powerhour#33]
I would like to address an issue which is relevant at least for the Norwegian users, who have day/night prices. When we close up on the clock to the time when price changes, the price + hours will not show correct price beyond the price change time, until the time passes, and the markup is updated from the flow. Is there any way to work around this?

@kmengvik see #27

**Comment by kmengvik** [comment]
Ok, thanks. Probably referring to this quote?

"But to answer your question: no I wont add the ability to import pricing via a flow. The DAP driver needs 3 x 24 hours worth of pricing to work (yesterday, today, tomorrow)."

So I guess that is the end of that then. I'll just accept that this will not work in the Kingdom of Norway?

**Comment by kmengvik** [comment]
Mmm yes! The other issues are solved. Thank you for all the work with that. Grid markup is quite simple. The rate has one value between 0600-2200, and the other value from 22-06. This means that the total grid price will jump up at 0600, and drop again at 2200. This markup is fixed until the grid company announce new prices. So static for months. But typically the level will be ajusted up during winter season, and lowered again in summer season. 
![image](https://user-images.githubusercontent.com/16176305/178359502-c572181e-8d77-47c0-84c2-df1c76a6eb3c.png)

**Comment by gruijter** [comment]
Ckear. This is only useful for Norway as far as I know. So Ill make you a deal. I am willing to add this feature if you are willing to translate the app to Norgwegian and also publish a seperate forum thread about how you use PBTH in your house.

Deal?

Ps: and as a translator you will be named as contributor to the app!

**Comment by gruijter** [comment]
Super!

I will start working on it then. You can also start working on the translation. I created a howto here: https://community.homey.app/t/65903

If the how-to is unclear or incorrect, please use the forum link to reply with your questions/remark!

**Comment by gruijter** [comment]
added in v 4.4.2. Please test and let me know :)

**Comment by kmengvik** [comment]
Works like charm. Ahead price takes a dive at 3+ hrs, at 2200.

![image](https://user-images.githubusercontent.com/16176305/178792191-53ecd97d-1579-49fb-8233-c2fc4bf029b7.png)

**Comment by kmengvik** [comment]
About the translating, I found that the README.no.txt copy was already created? And is this the text to translate? Perehaps better to ask somone who knows Dutch? I can only translate from English :)

![image](https://user-images.githubusercontent.com/16176305/178806038-73235951-7a30-4485-9d60-1384c917bb3f.png)

**Comment by gruijter** [comment]
I created that file already when testing for the translation manual. You can find the english version in the README.txt 😉

Good luck with the job and please use the forum if you have questions on the translation process.

**Comment by kmengvik** [comment]
Ok, thanks, on it already :)

**Comment by kmengvik** [comment]
> 

Found it: "

**Comment by gruijter** [comment]
Well don Kai!
