### ISSUE TITLE
Homewizard Energylink

### ISSUE THREAD

**Issue by avdl72** [gruijter/com.gruijter.powerhour#4]
I'm using the Energylink from homewizard with the Homewizard app. 
The Energylink is connect to the P1 meter and with S1 to the water meter and with S2 to the kWh meter for the solar panels.

It is not possible to select the gas meter because it isn't detected.
Also the solar panels can't be selected.
Also the data  from the P1 meter reading is the aggregated data which is used bij this app.

**Comment by avdl72** [comment]
The meter_power is now shown in the app field 'Huidige waarde'
<img width="549" alt="Schermafbeelding 2020-10-12 om 12 57 27" src="https://user-images.githubusercontent.com/34442008/95739285-e2802080-0c8a-11eb-9e9a-bc5135226ff9.png">

**Comment by gruijter** [comment]
The energylink app is using some none-standard capability extensions. If you can explain what is what, I might add special exceptions for it to powerByTheHour.

meter_gas_reading: is that the actual total gas reading as presented on the gas meter itself?

meter_power: what is the difference with meter_power.aggr? I expect meter_power to be the total of all 4 P1 power meters (consumed - produced). And what do you mean this is not shown in powerByTheHour? The red circled value should be presented when opening advanced device settings as actual reading.

Which capability shows the aggregated value of the solar panel via S1? 1.79 seems awefully low....

**Comment by gruijter** [comment]
I made a new version for you that should at least support gas. The solar panel via S1 is not possible for me, I can only read one meter_power per device.
The P1 power should already have worked, if not I don't understand what you you mean.

Please test it and let me know if gas works for you now.

https://homey.app/a/com.gruijter.powerhour/test/

**Comment by avdl72** [comment]
> The energylink app is using some none-standard capability extensions. If you can explain what is what, I might add special exceptions for it to powerByTheHour.
> 
> meter_gas_reading: is that the actual total gas reading as presented on the gas meter itself?
> 
> meter_power: what is the difference with meter_power.aggr? I expect meter_power to be the total of all 4 P1 power meters (consumed - produced). And what do you mean this is not shown in powerByTheHour? The red circled value should be presented when opening advanced device settings as actual reading.
> 
> Which capability shows the aggregated value of the solar panel via S1? 1.79 seems awefully low....

meter_gas_reading is the total gas reading from the meter.

I don't know what meter_power is and can not relate the value to another setting.
meter_power.aggr is day total 'Netto verbruik' in kWh.
meter_power.consumed.tx and meter_power.produced.tx is indeed the P1 readings from the slimme meter.

The value in the red circle is indeed presented in the details, but I doubt if it is the correct value.
Or maybe I don't understand the values right and the use of the app.

meter_power.s1 is the day total of the solar system.
And it is low as it was early in the morning and cloudy.

**Comment by avdl72** [comment]
> I made a new version for you that should at least support gas. The solar panel via S1 is not possible for me, I can only read one meter_power per device.
> The P1 power should already have worked, if not I don't understand what you you mean.
> 
> Please test it and let me know if gas works for you now.
> 
> https://homey.app/a/com.gruijter.powerhour/test/

Thank you.
I installed the test version and will let you know.

**Comment by gruijter** [comment]
> The value in the red circle is indeed presented in the details, but I doubt if it is the correct value. Or maybe I don't understand the values right and the use of the app.

That is the net total P1 meter to/from the grid. This is what PowerByTheHour needs to calculate your power usage/production to/from the grid. So that should already work.

**Comment by avdl72** [comment]
Is it correct that I filled the values in the setting like this?
![IMG_5657](https://user-images.githubusercontent.com/34442008/96458785-9fd9bd80-1221-11eb-845f-93ea5b007f4b.png)

And that gave me these weird 'deze maand' and 'dit jaar' values:
![IMG_5656](https://user-images.githubusercontent.com/34442008/96458865-b8e26e80-1221-11eb-8dd8-fe952a919325.png)

**Comment by gruijter** [comment]
This day start looks ok. If you have solar panels the numbers look right for this hour and this day.

But this month and this year do not look ok.
This month start should have the kWh value from 1.10.2020
This month start should have the kWh value from 1.1.2020

**Comment by avdl72** [comment]
> This day start looks ok. If you have solar panels the numbers look right for this hour and this day.
> 
> But this month and this year do not look ok.
> This month start should have the kWh value from 1.10.2020
> This month start should have the kWh value from 1.1.2020

I have done that.
Calculated both values together for meter_power.consumed.t1 and meter_power.consumed.t2

Did the same for the water meter and also here are minus values displayed.

And tested the gas readings and there are still no values displayed.

**Comment by gruijter** [comment]
Unless you have a nuclear power plant at home, I don't think you really produced 8MWh this month. The app just subtracts the present meter value from the one at the first day of the month.

And your water meter number is incredibly low.

Maybe your meters reset to 0 every day?

**Comment by avdl72** [comment]
This ain't gonna work for me.
Maybe in the future if I replace the Energylink for another suitable solution.

I wanna thank you for the support and this issue maybe closed.

**Comment by gruijter** [comment]
Thx. Have a good one.
