### ISSUE TITLE
Output to GUI is with mixed languages

### ISSUE THREAD

**Issue by kmengvik** [gruijter/com.gruijter.powerhour#45]
Hi. As I posted in PM the output from the master has flaws. I think perhaps the other day in the PM you did not fully catch what I am on about. I'll try to post some better examples here:

Initally, the text is displayed correctly in Norwegian from my translation:

![image](https://user-images.githubusercontent.com/16176305/180421791-abf2e562-2670-46e1-800d-2a3d476940cd.png)

However, when hoovered, the text is displayed in Swedish:

![image](https://user-images.githubusercontent.com/16176305/180422106-82e729a3-b545-4b57-9128-0ef664cf703b.png)

And, these hoovered textsm I can not find anywhere in the files. I kindly ask you to help me find where they are. As i said in PM, the search with ctrl-shift-F (Find in files) did not find anything.

![image](https://user-images.githubusercontent.com/16176305/180422511-33b7b537-deeb-4294-b3cf-afd04797e8a6.png)

The other issue I was on about, with the flowcards, I actually found the problem with on my own. I have fixed them in the fork now, but await your help with the hoovered texts :)

**Comment by gruijter** [comment]
How do you hover on the mobile app? Or are you talking about my.homey.app? Anyhow, that seems like a Homey bug, not an app thing. I cannot help you solve Homey bugs. Athom has a place to report those, but dunno where.

**Comment by kmengvik** [comment]
On the mobile app I hoover by tapping. And you are right! On the mobile the hoovered text is correct I can see now, it is on the web app it is screwed up. And I had no way to know that it is a homey bug. That is beyond my ability to guess. Inn that case I can deliver the latest PR for the no translation now then. But I have a kind request for some flow cards: Can you replace the € with option to insert local currency?

![image](https://user-images.githubusercontent.com/16176305/180438843-e2261b3b-3cfc-4305-b43a-dbca2def365d.png)
