### ISSUE TITLE
Need info for charging at right time

### ISSUE THREAD

**Issue by MisterOlsen** [gruijter/com.gruijter.powerhour#48]
Hi.

 I try to use PBTH, but I don't know how to, I live in Denmark and have setup, so it update Denmark prices, but I can't figure out how to set it up to my usage.

I come home between 15:00 and 18:00 and I need to charge the car for 3½ hrs before 6:00 in the morning, can you explain/guide me how to ?
I've a sensor saying when the car is home/plugged in ready to charge.

Kind regards, Thomas.

**Comment by gruijter** [comment]
Hi Thomas,

For these type of help questions the forum exists. Post your question there. Im sure there are people from Denmark that can help you!

https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535
