### ISSUE TITLE
trigger "then" price becomes XX% lower avg. this day

### ISSUE THREAD

**Issue by VitaliBabkin** [gruijter/com.gruijter.powerhour#49]
Hello and thank you for the app!

Please check  behavior triggers where a percentage is used. I see  "lower" works backwards 
test flow
![image](https://user-images.githubusercontent.com/20084345/184680857-5bca3368-d27b-4598-9836-4d0b0d067f71.png)
wrong trigger
![image](https://user-images.githubusercontent.com/20084345/184681058-0a5e595d-607a-49f3-9de8-cb2427902d29.png)

And also something wrong with "above". looks like it doesn't work.

Tnx.

**Comment by gruijter** [comment]
Is this only when using 0%? or also when using e.g. 10%?

**Comment by VitaliBabkin** [comment]
and 10% too.

trigger  "above"  I never see action and messages.  I think  it doesn't work
![image](https://user-images.githubusercontent.com/20084345/184974725-23f95fc7-6388-4ad0-b0a4-ddeff9a8958d.png)

**Comment by gruijter** [comment]
Ok, I think I found something wrong in my code. Will try to fix it and test.

**Comment by gruijter** [comment]
New version 4.5.2 should fix it: https://homey.app/a/com.gruijter.powerhour/test

**Comment by VitaliBabkin** [comment]
thanks! it's working fine now

**Comment by gruijter** [comment]
Super. Thx for the feedback!
