### ISSUE TITLE
Power by the Hour for HomeWizard

### ISSUE THREAD

**Issue by BertWi** [gruijter/com.gruijter.powerhour#5]
Hi, I have tested this App against my HomeWizard Energy. The gas reading works! 
The Power Summarizer does not work as it cannot detect any devices. The HomeWizard Energy App does show the energy readings (but only the current reading, not any daily or hourly totals).

**Comment by gruijter** [comment]
I will close this issue, since the homewizard app does not provide the meter_power capability that PBTH needs. You could ask the dev to add it to his app.
