### ISSUE TITLE
Using fixed and variable markup for dap

### ISSUE THREAD

**Issue by Gobbomaster** [gruijter/com.gruijter.powerhour#50]
When using both variableMarkup and fixedMarkup; it seems that the price is first multiplied with the variableMarkup and the fixedMarkup is added afterwards:
`let muPrice = ((price * this.settings.exchangeRate * (1 + this.settings.variableMarkup / 100)) / 1000) + this.settings.fixedMarkup;`

In reality (at least when using Tibber), the markup should first be added and the result should be used to multiply with the variableMarkup (tax).

Is there another way to configure this?

**Comment by gruijter** [comment]
The order is not configurable. But you dont need to either. Just add the tax to the fixed markup yourself before entering it in PBTH.

**Comment by Gobbomaster** [comment]
Thanks, I solved it by introducing a logic variable that multiplied the total with the tax. But this saves me a flow (and variable).
