### ISSUE TITLE
Qubino support?

### ISSUE THREAD

**Issue by LinuZitac** [gruijter/com.gruijter.powerhour#51]
Found a thread (below) where qubino is not supported. My Qubino device (ZMNHTD1) is selectable when adding a new PBTH-unit, but no data comes through. 
Any ideas if there's something i can do?

My Aqaria devices works flawless.

https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/367?page=19)

EDIT: It actually works if i change the setting "Use Watt as source".

**Comment by LinuZitac** [comment]
It actually works if i change the setting "Use Watt as source".

**Comment by gruijter** [comment]
Super!
