### ISSUE TITLE
Have you mixed kwh and money?

### ISSUE THREAD

**Issue by Sethakan** [gruijter/com.gruijter.powerhour#52]
When i choose to show money today the number showing is the kwh?

**Comment by gruijter** [comment]
Do ypu have a screenshot of what you mean!

**Comment by gruijter** [comment]
No feedback from you. Can I close the issue?

**Comment by Sethakan** [comment]
I answered, didn't i?

Yes close it👍

Håkan

Den ons 21 sep. 2022 12:17gruijter ***@***.***> skrev:

**Comment by Sethakan** [comment]
No im sorry, i mixed it all up.
It works as a charm🙏

Håkan

Den lör 10 sep. 2022 12:00gruijter ***@***.***> skrev:
