### ISSUE TITLE
please add a card to PBTH

### ISSUE THREAD

**Issue by emilkola** [gruijter/com.gruijter.powerhour#53]
today there is a card "Priset blir ett av **antal** lägsta under **period** timmarna före klockan **tid**" 
but it would be great if we also could have a card "Priset blir ett av **antal** lägsta under **period** timmarna mellan timme **x** och timme **y**" / "the price gets one of the lowest under **period** between hour **x** and **y**"

**Comment by gruijter** [comment]
I already have too many flow cards imo. You can easily achieve what you need with default Homey AND cards.
