### ISSUE TITLE
Percentage Flow Card - avarage price

### ISSUE THREAD

**Issue by andraves** [gruijter/com.gruijter.powerhour#54]
Would like the option to choose 5, 15, 25 and 35% in addition to today's values ​​of flow below/above the average price. Preferably the option to define the percentage myself

**Comment by gruijter** [comment]
Ill look into that

**Comment by gruijter** [comment]
Can you test the new version 4.6.1 and let me know if it works ok?

https://homey.app/a/com.gruijter.powerhour/test/

**Comment by andraves** [comment]
Hi!

I have used the test version through the night without being able to find any errors. Also tried different settings without finding errors.

Thank you very much for the support.

Sendt fra E-post for Windows

Fra: gruijter
Sendt: lørdag 1. oktober 2022 kl. 21:51
Til: gruijter/com.gruijter.powerhour
Kopi: andraves; Author
Emne: Re: [gruijter/com.gruijter.powerhour] Percentage Flow Card - avarageprice (Issue #54)

Can you test the new version 4.6.1 and let me know if it works ok?
https://homey.app/a/com.gruijter.powerhour/test/
