### ISSUE TITLE
Watt not updates 

### ISSUE THREAD

**Issue by Derbyb** [gruijter/com.gruijter.powerhour#55]
Why is not the watt in pbth update when the reported watt from my fibaro  plug updates in homey?

The reported watt from the plug is 0 w but in pbth says 409 watt. 

![477F7C95-C8F0-40E6-8F2E-77B9FA1EDC5F](https://user-images.githubusercontent.com/103101742/189231371-dc0ced59-7ddd-4854-95a9-f77e3f747ea3.jpeg)
![DCA10EEA-693B-4AB2-9A01-523AD7BDD708](https://user-images.githubusercontent.com/103101742/189231380-d1239969-3979-4c37-abf0-64115c79cc90.jpeg)

**Comment by gruijter** [comment]
PBTH is averaging the watts over a longer period. But when the source device is not using power it might take an hour before it is updated again. The usage and cost per hour/day/month should be correct though.

**Comment by FreddieO** [comment]
I have a very similar problem. It the power set to PBTH is very different from the variable its set by over the time span of 24h:
![image](https://user-images.githubusercontent.com/10044443/189517137-7f868318-53ad-4983-ba39-8f044224e1ab.png)
The average kWh reading is definitely wrong. I've scratched my head for a while now and can't figure out if i did anything wrong. The flows to set this is simple and it should be working: 
![image](https://user-images.githubusercontent.com/10044443/189517307-14e896f8-ec37-43bb-8b1d-c181d610c436.png)
Any ideas?

**Comment by dikal31** [comment]
I have problems with mine not showing the last penny in the amount, can you fix this? if the price is 6.06 min shows 6.01 instead of i price now.

**Comment by gruijter** [comment]
duplicate with #67

**Comment by gruijter** [comment]
Hope it is fixed in the new test version 4.8.2: https://homey.app/a/com.gruijter.powerhour/test

See also forum topic: https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/1040
