### ISSUE TITLE
Calculated/ measured values run wild and cannot be used

### ISSUE THREAD

**Issue by sandvest** [gruijter/com.gruijter.powerhour#56]
Hi,

Maybe this issue is reported or fixed but in version 4.5.6, is there a big problem with the measured values (see attached pic.). When this happens the app must be removed and added/ linked to the unit again. I have a feeling that this happens when the time passes 00.00, but not sure. The power app is not operational in this condition and can not be used. 

![example](https://user-images.githubusercontent.com/18185962/189873352-d94f6684-6625-4b8f-8ef4-4340eaa23679.jpg)

**Comment by gruijter** [comment]
It looks like your source device is providing corrupt kWh data. Check you Insights for that device.

If PBTH get garbage in, it will produce garbage out. You should contact the developer of the app / source device to fix this.

Alternatively, if the source device has a Watt meter, you could set 'Use WATT as source' in PBTH. In that case PBTH will  try to produce its own internal kWh meter.
