### ISSUE TITLE
“Price now” not working.

### ISSUE THREAD

**Issue by Mattdenmark** [gruijter/com.gruijter.powerhour#57]
it seems that all cards where you have to put 
A variable by yourself does not work. When using below average everything seems fine, but “Price now get led than” is not working?
I did ask i a Danish Forum and it seems im not the only one experience this problem.

Regards Mathias.

![6AD8B780-6C3B-415A-A491-D98F8C60992D](https://user-images.githubusercontent.com/113938858/191093859-4bf29e13-2720-4906-86c6-698e5129a4a6.png)
![D940F6E5-0CA2-4C49-B042-006AE6FA6BEF](https://user-images.githubusercontent.com/113938858/191093874-9e52b7a7-7104-4c0e-9b4a-9bd2f3ef9e81.png)

**Comment by gruijter** [comment]
This is a Homey native function. I do not manage the coding for it. So please create an issue with Athom.

By the way: you do know that it is supposed to only trigger when is goes below the set value? So not when it already was below that value!
