### ISSUE TITLE
Update van "totaal" Qubino 3-phase Smart Meter werkt niet

### ISSUE THREAD

**Issue by edegoede** [gruijter/com.gruijter.powerhour#58]
Als ik een PBTH aanmaak van het totaal van mijn 3 fase meter (Qubino), dan krijg ik geen waardes door.
Wel als ik de 3 fases afzonderlijk doe, maar het totaal dus niet (zie screenshots).
Kan dit opgelost worden aub?
Vriendelijke groet,
Edwin
<img width="543" alt="Schermafbeelding 2022-09-21 om 09 47 55" src="https://user-images.githubusercontent.com/114059429/191448073-091470df-e573-41b5-8a53-0a9c7eafda1b.png">
<img width="429" alt="Schermafbeelding 2022-09-21 om 09 47 47" src="https://user-images.githubusercontent.com/114059429/191448098-7457b892-38db-44e1-8dc1-92828f18af22.png">

**Comment by gruijter** [comment]
Use the <GROUP> app to combine the kWh of the 3 phases, and then add that virtual device to PBTH.
https://homey.app/en-gb/app/com.swttt.devicegroups/&lt;-group-&gt;/

**Comment by edegoede** [comment]
Helaas gaat dat alleen met de kWh, het geld wordt niet meegenomen in de groep.

**Comment by edegoede** [comment]
Helaas gaat dat alleen met de kWh, het geld wordt niet meegenomen in de groep.
