### ISSUE TITLE
Power Meter only finds Fibaro Roller Shutter Devices

### ISSUE THREAD

**Issue by theduqueduque** [gruijter/com.gruijter.powerhour#6]
Hello There

I tested your Homey App, since Homey cannot produce power consumption information cumulated.
The app works for the devices it finds, but not for my Power Meters. I have the following Power Meters in place
myStrom Power Adapter (they also have a Homey App). Will these Power Adapters work with your app in the future?

I am also planning on installing a smart meter by the circute board. So now I am wondering if you know which of these smart meters you have supported already
Qubino 3 Phase Smart Meter
Shelly 3EM or 4Pro Smart Meter

Thank you and best regards
Alex

**Comment by gruijter** [comment]
Any app that has a meter_power capability should appear whdn trying to pair. Ask the developer if he has this capability.

**Comment by theduqueduque** [comment]
OK thank you for the Information, I will ask the Devs on myStrom if that is possible
Also will ask Qubino and Shelly on that.

Best regards
Alex

**Comment by theduqueduque** [comment]
Thank you again for your insights into this function.
Will it be possible to selected multiple devices and show it as 1 tile?
e.g select all my discoverd devices by your app and display the values from all those devices as 1 tile?

Right now I always can only select a single device and press "next"

Thank you and best regards
Alex

**Comment by gruijter** [comment]
You can use this app to group devicex together into a virtual device: https://homey.app/nl-nl/app/com.swttt.devicegroups/&lt;-group-&gt;/

See also the forum about this solution

**Comment by theduqueduque** [comment]
Hello gruijter

Of course, i am already using this app for a lot of things. I have connected the dots that I could use it for your app too.
Thank you for pointing me in the right direction.
Best regards
Alex
