### ISSUE TITLE
Time window variable gas price.

### ISSUE THREAD

**Issue by Stekel55** [gruijter/com.gruijter.powerhour#62]
Dear Robin,
Variable gas price have a prive window from 06.00hr to 0.600hr each day. I don’t think you have implemented that.

Is it an idea to input the price as hourly prices from:
00.00hr to 06.00 with the day price of the previous day, and
From 06.00hr tot 24.00hr of the todays price?

How do you think about that?

**Comment by gruijter** [comment]
Gas prices are already implemented from 6 to 6 next day. What is not working according to you?
