### ISSUE TITLE
Goedkoopste periode energieprijzen

### ISSUE THREAD

**Issue by edegoede** [gruijter/com.gruijter.powerhour#65]
Ik kan in PBTH zien welk uur het laagste kWh-tarief is. Maar kan ik ook zien welke periode van bv 4 uur de goedkoopste periode is, om daarmee een schakeling van apparatuur te maken?

**Comment by gruijter** [comment]
Yes. You can start a flow for exactly that. You can select chrapest 4 hours of the day, cheapest 4 hours before a certain time, cheapest consecutive (=average) hours, and many other selections. If you need help please go to the forum.
