### ISSUE TITLE
No data from HomeWizard

### ISSUE THREAD

**Issue by perpatrik79** [gruijter/com.gruijter.powerhour#66]
A few days ago, the app siezed retrieving data from HomeWizard. I am running version 4.7.2.

**Comment by gruijter** [comment]
What data did you have before that is now missing? Do you have screenshots or insight logs that show and explain to me what your issue is?

**Comment by perpatrik79** [comment]
Hello!

Below, you can see my problem. I use the app to monitor the
accumulated electricity consumption on a monthly basis. Up until the 20th
of october the data kept flowing in and the consumption was accumulating.
On that date, however, the curve went flat and no more data was
being retrieved.

As I prepared my answer to your question, I realized that the "total usage"
variable in the HomeWizard-app seems to have seized producing data about
the same time as the consumption stopped accumulating in your app (I was
looking at the "total T1 usage"-variable when I came to the conclusion that
the HomeWizard-app was functioning correctly).

Thus, it seems the problem is in the HomeWizard-app. I am sorry to have
bothered you with this.

Sincerely,
Patrik

[image: image.png]


Den tis 25 okt. 2022 kl 17:35 skrev gruijter ***@***.***>:
