### ISSUE TITLE
kWh increasing while device is not consuming power

### ISSUE THREAD

**Issue by BertWi** [gruijter/com.gruijter.powerhour#67]
Hi Robin,

thanks for your excellent work on this App so far!

I'm experiencing some strange behaviour with some of my Wifi smart plugs connected to my Homey via the Tuya Cloud App. They just keep on aggregating the kWh values, while the device itself does not consume energy. I can only use Watt as a source and I now that is not as accurate, but this is really strange. See attached graphs.

![Graphs](https://user-images.githubusercontent.com/70894809/197569116-d9be8f58-a5ee-49b3-ae21-85601b538a85.PNG)

I have 6 of those devices, 4 of them are working properly and 2 of them are showing this odd behaviour. They are even of the same brand, where 1 is working good and 1 is showing this odd behaviour. The values in my Tuya Smart App show correct values, so it is not a connection error from the device itself.

Any idea?

Thanks!
Bert

**Comment by gruijter** [comment]
Thx.

Will need to dig into this. But I have many other priorities, so please be patient :)

**Comment by BertWi** [comment]
Thanks Robin. I will be patient ;-)

**Comment by ludwich** [comment]
Have the same issue.
![image](https://user-images.githubusercontent.com/2908644/198594068-122a2f15-1dc2-45dc-a2a2-2a78a9ada170.png)

**Comment by runecarlsen** [comment]
This is exactly the same as I have posted in my recent post. Did anything come out of this? I have the same problems!

**Comment by Moardeth** [comment]
![IMG_0490](https://user-images.githubusercontent.com/119499681/204787431-77f45997-391c-48e3-8a94-6556535662b8.PNG)
I have the same issue, can only use Watt as source. Here it starts at 12:00

**Comment by gruijter** [comment]
Hope it is fixed in the new test version 4.8.2: https://homey.app/a/com.gruijter.powerhour/test

See also forum topic: https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/1040

**Comment by gruijter** [comment]
is confirmed to work by @runecarlsen

**Comment by BertWi** [comment]
Hi Robin, I can also confirm it is now correctly working! Thanks for your efforts!
