### ISSUE TITLE
Wintertime bug?

### ISSUE THREAD

**Issue by lawrenz89** [gruijter/com.gruijter.powerhour#69]
Hi, I noticed that the price was wrong by one hour today when we went into winter time by setting the clock one hour back. How does this get fixed? Will it get fixed by itself tomorrow maybe?

**Comment by gruijter** [comment]
Tomorrow all will be good. See forum for permanent fix in the new version I created 
https://homey.app/a/com.gruijter.powerhour/test

**Comment by lawrenz89** [comment]
> Tomorrow all will be good. See forum for permanent fix in the new version I created
> https://homey.app/a/com.gruijter.powerhour/test

Perfect!
