### ISSUE TITLE
Power by the Hour - Gas meter reset

### ISSUE THREAD

**Issue by Vetjes** [gruijter/com.gruijter.powerhour#7]
For the electrical part, I'm able to select the 'has a daily reset' checkbox, so my totals won't become negative. For the gas meter I'm not able to do this. Would it be possible to also add it in the Gas totalizer?

**Comment by gruijter** [comment]
Can you explain the use case? For power it is needed in case the power meter always resets to 0 every day. That behaviour is common for certain solar panel meters. But what kind of gas meter would reset to 0 every day?

**Comment by Vetjes** [comment]
I had it connected to Domoticz through the Domoticz-app, that's where the value of the gas meter is being reset daily. However, I didn't want to keep domoticz running only for that purpose so I switched to Homewizard P1 so the request is not active anymore.

**Comment by gruijter** [comment]
Ok. Will close the issue then.
