### ISSUE TITLE
Power not correct updated with use off virtual sensor

### ISSUE THREAD

**Issue by Wiltjer** [gruijter/com.gruijter.powerhour#70]
Power not correct updated with use off virtual sensor. 
![4A961971-592A-4768-9E1F-4A9A1F7F7A94](https://user-images.githubusercontent.com/45851798/199115142-20ca3832-d677-40f0-973a-080de8642108.jpeg)

**Comment by gruijter** [comment]
What am I looking at here? Which values are incorrect in PBTH? Which one is the virtual device?

FYI: PBTH is not primarily meant to track power (Watts). PBTH is averaging watts over a 2 minute period, so the watts can differ slightly from other Watt trackers.

Closing this issue now, but please reopen if you think there is a bug.

**Comment by Wiltjer** [comment]
Hello,

 

The device called “Laadpaal” is on “zero” (0 watts) for hours, but the PBTH app had missed that and keeps on registrating the 5498 Watts.

Witch results in a much higher cost/day than the actual value 

 

Regards,

 

Ben

 

Van: gruijter ***@***.*** 
Verzonden: zaterdag 3 december 2022 12:34
Aan: gruijter/com.gruijter.powerhour
CC: Wiltjer; Author
Onderwerp: Re: [gruijter/com.gruijter.powerhour] Power not correct updated with use off virtual sensor (Issue #70)

 

What am I looking at here? Which values are incorrect in PBTH? Which one is the virtual device?

FYI: PBTH is not primarily meant to track power (Watts). PBTH is averaging watts over a 2 minute period, so the watts can differ slightly from other Watt trackers.

Closing this issue now, but please reopen if you think there is a bug.

**Comment by gruijter** [comment]
Hope it is fixed in the new test version 4.8.2: https://homey.app/a/com.gruijter.powerhour/test

See also forum topic: https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/1040

**Comment by Wiltjer** [comment]
I will test it and keep you informed.

 

Grtz,

 

Ben

 

Van: gruijter ***@***.*** 
Verzonden: zondag 4 december 2022 14:29
Aan: gruijter/com.gruijter.powerhour
CC: Wiltjer; Author
Onderwerp: Re: [gruijter/com.gruijter.powerhour] Power not correct updated with use off virtual sensor (Issue #70)

 

Hope it is fixed in the new test version 4.8.2: https://homey.app/a/com.gruijter.powerhour/test

See also forum topic: https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/1040
