### ISSUE TITLE
+1h under/over X% and-cards?

### ISSUE THREAD

**Issue by lawrenz89** [gruijter/com.gruijter.powerhour#71]
Hello! 
There is a and-card where you can choose “price is x% below or above todays average”. Possible to add the same card but with +1h? 
“Price +1h is x% above/below todays average”.
Would be really useful for me and my fellow friends and much appreciated :)

**Comment by gruijter** [comment]
If you still need this, please post it here: https://community.homey.app/t/app-pro-power-by-the-hour-feature-requests/69740
