### ISSUE TITLE
TTF Gasprijzen worden niet meer geupdate

### ISSUE THREAD

**Issue by LecramRed** [gruijter/com.gruijter.powerhour#72]
De TTF gasprijzen worden sinds drie dagen niet meer geupdate. De stroomprijzen wel. Ik heb de app gereset, maar dat geeft geen verbetering.

![Schermafbeelding 2022-11-05 111837](https://user-images.githubusercontent.com/100309229/200115035-956f9db7-4e88-448f-876a-6327a61a5637.jpg)

**Comment by gruijter** [comment]
If TTF service provider is down, there is nothing I can do. You just need to wait until they come online again.

Note: I already made a feature request to have a second / different source of gas prices: https://community.homey.app/t/69740/54
