### ISSUE TITLE
Update current Engery price via flow

### ISSUE THREAD

**Issue by GabrielKoetsier** [gruijter/com.gruijter.powerhour#74]
Good morning,
Love your app, but since last update there seems to be an issue in adding a current energy price via an flow. It is not changing anymore.

Example flow below which is not updating the price, use this for piek/dal pricing. As said this flow is just to test if update is working but is not updating. 
Hope we can get this working soon again

Thanks coop Gabriël
![Screenshot 2022-11-07 10 22 47](https://user-images.githubusercontent.com/117637444/200275626-589135f3-e8b4-4213-9c8e-affd279b6268.png)

**Comment by gruijter** [comment]
Thx!

You havnt set a tariff group. See the forum for details.
