### ISSUE TITLE
Send <Energy (kWh)> reading to <Virtual Device> for <DateTime>

### ISSUE THREAD

**Issue by mtudor** [gruijter/com.gruijter.powerhour#76]
This may be hard, depending on how the app is implemented, but I would find it useful to be able to populate values in the past when sending a reading.

I am trying to use Power by the Hour to track the energy usage of my entire house, using the API of my energy supplier.  I can get half-hourly consumption data, but only after around 1 am the following day (so not live).

Am I missing an easier way to do this?  Or would a functionality to populate values at times in the past be possible?

**Comment by gruijter** [comment]
That wont be possible with PBTH. But you could at least upload the new total kWh when you receive it (so not per half hour, but per day). That way you will get a report of totals per day/month/year, albeit shifted a day.

**Comment by mtudor** [comment]
Thanks for the quick response.  I suspected that might be the case, but if it's something that could be incorporated in the future then I think it would be pretty useful for advanced cases.  Appreciate it might be a complete change of architecture and therefore right at the bottom of (or off!) any list!

In the meantime, I think you're right that submitting when I have the data, shifted a day, is the best compromise.  Just one thing to check - I am on an economy seven (two-rate) power plan.  Will it work for costings if I write a flow that basically goes:

START -> Change plan to day rate -> Submit energy reading for day hours -> Change plan to night rate -> Submit energy reading for night hours -> END

I'm guessing it probably will but just thought I'd check (and also leave this here for anyone that finds this issue in the future as a potential solution!).
