### ISSUE TITLE
Timeline not correct (lowest price)

### ISSUE THREAD

**Issue by jibbedeg** [gruijter/com.gruijter.powerhour#78]
Hi Robin,

I am using PBTH, but I noticed the lowest price for the next 4 hours is not correct.
What I want to use is: The lowest 4 (connected) hours of a day, and charge some of my utilities for that moment.
But I am having difficulty finding "The lowest 4 connected hours of a day).
Which function of PBTH should I use there?

Cause with this one I am not getting the right moment out of it:

<img width="543" alt="Schermafbeelding 2022-11-08 om 08 07 40" src="https://user-images.githubusercontent.com/117714419/200500555-f062f509-f133-4f46-b41d-192f691f667f.png">

<img width="932" alt="Schermafbeelding 2022-11-08 om 08 09 50" src="https://user-images.githubusercontent.com/117714419/200500598-cfca1d45-4ffc-4704-92e2-b532f309fc82.png">

And it gave me a message on 08:00 hrs (while the graph is on the way up).

Please let me know what to use.

Kind regards,

Jibbe

**Comment by gruijter** [comment]
Use the card for lowest average price
