### ISSUE TITLE
Gasprijs van meer dan €15.000.-

### ISSUE THREAD

**Issue by MartinvD1** [gruijter/com.gruijter.powerhour#81]
Sinds de update van 2 dagen geleden heb ik een gasverbruik met de kosten van meer dan €15.000,-. Het lijkt erop dat hij de meterstand gebruikt i.p.v. het verbruik van de dag.

**Comment by gruijter** [comment]
I suspect your kWh meter had a faulty reading. Check your Insights for a big dip in the source kWh value.

**Comment by gruijter** [comment]
please reopen if you still have issues in latest v5
