### ISSUE TITLE
1% higher

### ISSUE THREAD

**Issue by jibbedeg** [gruijter/com.gruijter.powerhour#82]
Hi Robin,

The Card: Price will be 1% (or other %) higher then average of this day (or upcoming 8 hours) isn't correct.

<img width="242" alt="Schermafbeelding 2022-11-22 om 08 02 11" src="https://user-images.githubusercontent.com/117714419/203247549-4b0bfba4-3649-4abb-ae88-9d44b92ce42a.png">

It doesn't do anything and I think why it it. It only triggers if the amount will be exactly 1%. But what I need (and I think what you mean by this card) is when it will turn BIGGER then 1% over the average, a trigger is made (that's what I need anyway).
Could you change it to work correctly, or make another triggercard for that occasion?
Please let me know.

Jibbe

**Comment by gruijter** [comment]
It should already work when larger then 1%. So im not sure what is going on.

**Comment by jibbedeg** [comment]
Is it possible for you to check if it works ok?
Cause I don’t get a notification on just the trigger.

Kind regards, Jibbe

**Comment by jibbedeg** [comment]
Doesn't work, could you please check it? Same goes for "lower then average".
And some other triggers which don't work the way they should in PBTH (or I might do something wrong):

<img width="677" alt="Schermafbeelding 2022-11-24 om 13 12 57" src="https://user-images.githubusercontent.com/117714419/203782154-42e097bd-a515-4d59-8d94-604663cc87b2.png">

On this flow every day the price is 0,16 euro per kWh, but it should vary, and I haven't put a fixed price in the app (only variable of 0,0954 euro and 9% Tax). So how come every day is the same price for a kWh?
How will I get the right result of a price which is build up by differtent hourly rates?

And finally: I would like to have a flow where 4 priced CONNECTED hours will be the lowest of the day and before/after 12:00 hrs (cause the line of the EPEX is almost always build up in 2 flows on a day). Will it be possible to make this? Cause it doesn't exist at this moment.

Please let me know, then I can use them properly.
Thanks!

Jibbe

**Comment by jibbedeg** [comment]
I think I found it:

The Power summary's of each machine/device is registered with an "Active MoneyRate" (actief tarief). He is getting that from the P1 (slimme meter). But, on the P1 you can't get an hourly rate, so it should be taken out of the PBTH NL_Netherlands part each hour. Will this be possible to change?

Jibbe

**Comment by gruijter** [comment]
If you still need this, please post it here: https://community.homey.app/t/app-pro-power-by-the-hour-feature-requests/69740
