### ISSUE TITLE
PBTH summarizer goes wrong

### ISSUE THREAD

**Issue by runecarlsen** [gruijter/com.gruijter.powerhour#83]
I have been using PBTH for a while, and it works just perfect. 
But there is a problem with one kind of my devices. These are a smart plug of this version, "Apex Smart Plug". 
What happens is this; 

1. It is regardless what kind of device that is attached to the Apex. 
2. When I turn it on, - the power/energy consumtion on the device and power/energy summarizer on the PBTH-device looks ok (using Homey insights)
3. When I turn it off, - then the power/energy consumption on the device also stops (using Homey Insights)
4. BUT, the power/energy summarizer of the PBTH-device keeps on consuming/increasing/summarizing. And it increases for every hour, even when the device is turned off! 
5. Meaning, if i have the device turned on 1 hour, it looks all ok on the insight for the device it self, but for the PBTH-summarizer device, it keeps increasing for every hour. 

I have attached a screendump of the insights showing exactly the above, and it shows that I turned on the smartplug (which has a heater attached in this example) and I kept it ON for just about 30minutes. As you can see on the top graph, all looks as it should. The summarizer graphs are though in some kind of loop.... 

regards, 
Rune

![bug-pbth01](https://user-images.githubusercontent.com/118962695/203719441-06e3ab2b-4b8b-4bc0-9417-38b4076ae705.PNG)

**Comment by runecarlsen** [comment]
Is there a developer following up on these posts?

**Comment by gruijter** [comment]
Yes, but I lack spare time at the moment. Please be very patient 😘

**Comment by runecarlsen** [comment]
Oh, thanks for at least answering. I can see that this issue has connection with a previous mentioned issue, from October. I really hope you can have a look at it, as I have MANY of these issues :(

**Comment by runecarlsen** [comment]
So, the story goes :) 

![image](https://user-images.githubusercontent.com/118962695/205073569-028a7a44-111a-498d-adbe-60dcffd5d6a4.png)

This is not in use and turned off.... but it is still summarizing and increasing....

**Comment by gruijter** [comment]
Thx for all the input 🤗

It is clear I need to figure out where in my app this goes wrong (aka: find the bug).

But please be very patient because I dont see any spare time for this for a while.

**Comment by runecarlsen** [comment]
Thats too bad :(

**Comment by gruijter** [comment]
closing this. issue is same as #67

**Comment by gruijter** [comment]
Hope it is fixed in the new test version 4.8.2: https://homey.app/a/com.gruijter.powerhour/test

See also forum topic: https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/1040

**Comment by runecarlsen** [comment]
Currently testing. Will let you know! :)

**Comment by runecarlsen** [comment]
Verified, - works! :) 

Thank you so much!

**Comment by gruijter** [comment]
Super, thx for testing and letting me know! I will release it as stable then 😊
