### ISSUE TITLE
DAP Status indicator 

### ISSUE THREAD

**Issue by ECKEROTH** [gruijter/com.gruijter.powerhour#84]
After update 4.9 my DAP shows wrong status indicator regardless what I save

**Comment by gruijter** [comment]
Di you have a screenshot of what status indicator you mean?

**Comment by ECKEROTH** [comment]
It is actually only on my IPad that there is a problem with the status indicator on the icon. Should know 'Money This Day SEK' but shows kWa. On both iPhone and iPad, the SEK symbol is displayed incorrectly after 4.9.0
![CA36C848-43CF-4CF2-A259-08464C131285](https://user-images.githubusercontent.com/10584519/205946678-f9876ee9-61b4-4771-803a-aacd7dabdbb4.jpeg)
![6D24EFA3-0D7C-44ED-989C-9578C9253C2B](https://user-images.githubusercontent.com/10584519/205946703-0559b55d-6694-46a4-bca5-1ddef0d3fc1e.jpeg)

**Comment by gruijter** [comment]
Did you try fully closing the Homey app on your ipad? Did you try reboot of Homey?

**Comment by ECKEROTH** [comment]
No I did not 👎🏻 I actualy never close any apps in my Apple unverse .
Now I did, and it fixet the status indicator 👍🏼 but SEK is still missin as Isee ¤ instead.

**Comment by gruijter** [comment]
I think I found the bug in the migration code for currency symbol. Will be fixed in the next release.

Thx for reporting!
