### ISSUE TITLE
Currency unit not working in 4.9

### ISSUE THREAD

**Issue by Helsbol** [gruijter/com.gruijter.powerhour#85]
In 4.9 the currency unit do not display correctly on the power meter Tiles.

![image](https://user-images.githubusercontent.com/119938050/205897870-77a0b71a-4ce4-4504-985f-9523cca0e329.png)
![image](https://user-images.githubusercontent.com/119938050/205898009-2a0bf0a1-9adc-4b2b-8f98-e32594fd7c91.png)

It do however work on the Price tiles.
![image](https://user-images.githubusercontent.com/119938050/205898695-a2eba068-84d8-4ded-970d-547160414d1b.png)

**Comment by gruijter** [comment]
V5 has been released as stable. If problem still exists please reopen the issue.
