### ISSUE TITLE
Feature Request: Add capabilities of the Qubino 3-Phase SmartMeter

### ISSUE THREAD

**Issue by dirkg173** [gruijter/com.gruijter.powerhour#86]
Hi Robin,
I bought a Qubino 3-Phase SmartMeter. I would like to use this in PBTH without going through the workaround of a virtual device and additional flows and without using the wattage option as it is more inaccurate.
The problem why the Qubino SmartMeter doesn't work with PBTH by default is that the Qubino app uses other capabilities.
PBTH uses:
`meter_power`
Qubino app uses:
`meter_power.import`
for power consumption (import).

The Qubino app/the SmartMeter has also the capability, to report the export of wattage with the following capability:
`meter_power.export`

The Qubino 3-Phase SmartMeter is also used by other users, as you can see in the forum.
Would it be possible to implement these two capabilities in the code?

Best regards
Dirk

**Comment by gruijter** [comment]
So all Qubino meters have both meter_power.import AND meter_power.export?

And can the total used energy be calculated by (meter_power.import - meter_power.export)?

What is the appId of the qubino app?
Do you have a github link to the source?

Can you please add a reference to this feature request on the forum here: https://community.homey.app/t/app-pro-power-by-the-hour-feature-requests/69740

**Comment by dirkg173** [comment]
Don't know if other Qubino devices have both `meter_power.import` AND `meter_power.export`?
The Qubino 3-Phase SmartMeter is the only Qubino device I use. Maybe the Qubino 1-Phase SmartMeter has also both capabilities.

Some information:
`meter_power.import` is the total used energy. When energy is fed into the in-house power grid, e.g. by a solar system, and consumed, the power is not supplied via this capability.
`meter_power.export` means that energy was fed into the public grid, e.g. by a solar system.
So I guess there is no need to calculate something.

Don't know the AppID of the Qubino App. How can I find out?

No, I have no GitHub link to the source code, because the app is developed by Qubino itself.

So if you need any further or more detailed information, I can write to Qubino support and ask.

**Comment by dirkg173** [comment]
App-ID: com.qubino@4.1.1

Concerning the calculation: I don't quite understand it, because `meter_power.export` shows exactly the value when you start earning money.
`meter_power.import`: You have to pay
`meter_power.export`: You will be paid

**Comment by gruijter** [comment]
is implemented in v5
