### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by markussandin1** [gruijter/com.gruijter.powerhour#88]
What I want to do is probably described in this screenshot, but i get a 403 when clicking on it. ![image](https://user-images.githubusercontent.com/19946298/208308326-8b480a09-93ab-4f47-a9fa-82008e37d6b7.png)

**Comment by gruijter** [comment]
Werd. I can see the image.
https://global.discourse-cdn.com/business4/uploads/athom/original/3X/4/d/4d66a18295c0e18112eed0150d22ca9864a2773c.jpeg
