### ISSUE TITLE
Sudden unexplained peek in kWh prev. hour

### ISSUE THREAD

**Issue by EirikFaerdin** [gruijter/com.gruijter.powerhour#89]
Last night I got a value for kWh between 2 and 3 of 146.79 kWh from my Tibber pulse. Normal at that hour is 5-6 kWh. Checking the PbtH dashboard, I also found the min and max watt readings off the scale, as obvious from the screenshot below.
![image](https://user-images.githubusercontent.com/77051797/208534136-43e76beb-a819-4c77-8dd3-f105347516e6.jpeg)
Best regards,

Eirik S

**Comment by gruijter** [comment]
what version app are you using?
Can you post the kWh insights graph of the tibber source device that includes that moment? I could explain this behavior if the kWh meter had a short dip. Or when the (connection to) the source device was offline for a long period.

**Comment by EirikFaerdin** [comment]
The app version is 4.9.1.

There's no tell-tail looking at the Tibber consumption for this period, but this was maybe not what you meant?
![image](https://user-images.githubusercontent.com/77051797/209235872-52f7e141-1445-4feb-836e-2f2665bfdac1.jpeg)

**Comment by gruijter** [comment]
Hi Erik
I meant the Insights from the tibber pulse device in Homey.

**Comment by EirikFaerdin** [comment]
Sorry, I had completely forgotten about that 🫢 

I had a similar thing happening today, and was able to gather some more relevant data.

Here's a screenshot from the app:
![image](https://user-images.githubusercontent.com/77051797/209470448-7eaa7dc4-dec7-49c0-9aca-817503774dfe.jpeg)

According to Homey insights, Homey was not receiving data from Tibber pulse for a few hours this morning:
![image](https://user-images.githubusercontent.com/77051797/209470517-7d325c43-a474-4562-b34f-c79544a4f58c.jpeg)

Also, the Tibber app missed data, but only for one hour:
![image](https://user-images.githubusercontent.com/77051797/209470553-b67b8462-6028-4fcf-9956-a90df4e26c04.png)

Checking the Wi-Fi connection (Ubiquity UniFi), there's no indication the Tibber pulse were offline:
![image](https://user-images.githubusercontent.com/77051797/209470642-1c73627d-cc4e-40b4-b7f3-25912cc35f6a.jpeg)

Hope this helps 😃 

Best regards Eirik

**Comment by gruijter** [comment]
Does Tibber Pulse only have a Watt in Homey, no kWh?

**Comment by EirikFaerdin** [comment]
Current power is in W while consumption is in kWh:
@![image](https://user-images.githubusercontent.com/77051797/209473583-69d09e89-2085-4959-88eb-e54698420887.jpeg)

**Comment by gruijter** [comment]
I need to see the Tibber Pulse kWh insights graph (consumption) for today.

**Comment by EirikFaerdin** [comment]
Hope these are what you're looking for:
![image](https://user-images.githubusercontent.com/77051797/209474094-e9ec44b6-f095-472d-90c9-b51746a6b7af.jpeg)

![image](https://user-images.githubusercontent.com/77051797/209474098-4ff4714f-38e1-4021-b70c-1df3bcd4629c.jpeg)

**Comment by gruijter** [comment]
So at noon today PBTH should have seen a big spike in Watts because the Tibber kWh suddenly jumped approx 20kWh.
And it would also explain a PBTH energy usage of around 20-30 kWh between 12 and 13hrs. Does PBTH indeed show that figure?

If so: PBTH is working as it should. Tibber is losing 'connection' for hours at a time, and PBTH will assign all energy from those missing hours to a single moment. Solution lies in getting a more reliable metering into Homey, without missing hours.

**Comment by EirikFaerdin** [comment]
Yes, you're right. Not sure why the data was lost though since Homey continued to receive from other devices.
Anyway, would it be a way for PBTH to e.g. average the consumption over the "disconnected" period?

Also, is there an explanation why the max watt (and min in my first example) readings are so far off? Could it be that when connection was restored, it calculates the power needed to instantly jump from last recorded kWh? If so, maybe that could be something to look into?
Anyway, thanks for an amazing app, it really brings great value!

Best regards Eirik

**Comment by gruijter** [comment]
PBTH already averages out. But disconnections this long are very unusual. And besides I believe that the Tibber app is not giving any clue that it is disconnected. It just keeps reporting the old value until it suddenly jumps to a new value.

I will close this issue for now. Hope you can get support from Tibber. Or alternatively you could add a second more reliable P1 reader using a splitter. E.g. Youless or Plugwise.
