### ISSUE TITLE
Feature request: Detect also sub-capabilities from meter_power

### ISSUE THREAD

**Issue by oh2th** [gruijter/com.gruijter.powerhour#96]
There are devices that may have [sub-capabilities](https://apps.developer.homey.app/the-basics/devices/capabilities#using-the-same-capability-more-than-once) for meter_power.

It would be useful, if PbtH would detect also the sub-capabilities of meter_power. For example a go-eCharger that has
* one master meter_power counter for total energy usage
* a sub meter_power.session counter for each charging session
* 1-10 RFID card based meter_power.(1-10) one counter for each registered RFID card.

**Comment by gruijter** [comment]
This will make the software code and the user setup too complex IMO. You can already achieve what you want by setting up a PBTH  virtual device(s), and fill the device with kWh values via a flow.
