### ISSUE TITLE
 2 OF THE SAME FLOW CARDS

### ISSUE THREAD

**Issue by DUMSKALLE45** [gruijter/com.gruijter.powerhour#97]
I noticed that it is the same text on 2 of the AND cards ,(The price is one of(number) lowest of today. But should have had one with Highest today.

![HOMEY](https://user-images.githubusercontent.com/121627367/209976810-92f79c32-212d-46d5-9e58-4b98002e24b7.jpg)

**Comment by gruijter** [comment]
see here: https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/1080

Will be fixed in v5
