### ISSUE TITLE
Bug with Heavy Duty Switch

### ISSUE THREAD

**Issue by runecarlsen** [gruijter/com.gruijter.powerhour#98]
I know this doesnt apply for all users, as I have seen users that does not have this problem, but, then it must be something related to config or anything else. I am open for comments or guidance, or in best case, a fix, if this infact is a bug. 

So, lets have a look at a "normal" device that works, and how the device itself shows the effect/usage, and how PBTH shows its values; 

![image](https://user-images.githubusercontent.com/118962695/210150034-be025a0e-cf89-466b-8c1e-8bc2d66de242.png)

As we can see. PBTH recognizes the device being turned on (this is a smart plug) and for the sum it keeps the value, and increases again the next time. 

Now, have a look at how this does look on my Heavy Duty Switch; 

![image](https://user-images.githubusercontent.com/118962695/210150085-be9e7259-79bd-41c7-a160-6d1e0e91f977.png)

As you can see, the timing is all wrong. And it doesnt keep the levels. It goes down to 0 again, before it jumps up to another level. 

So what is the problem with this? 

Well, if I in Homey at a certain time, gets the value for the usage TODAY, and the PBTH device at that time shows 0 as value, it is completely wrong, when it should have been alot more... 

I have tried to demove the PBTH device, and re-add it. i have tried to uninstall PBTH, re-install it. Nothing heps. Restarted Homey. Nothing work. It is the same all over. I have checked the settings of the Heavy Duty Switch, and I have tried both default settings, which should be ok, - as well as copying some friends settings. Same whatever I do. Nothing works. 

Please help. This is really a big problem. And it is ONLY a problem with Heavy Duty Switch (as far as i can see right now). 

Rune

**Comment by runecarlsen** [comment]
My understanding, and how other devices work, is that they should be connected, and dont drop down to 0, like this; 

![image](https://user-images.githubusercontent.com/118962695/210164110-0fef6374-3676-4b0a-bdfe-6037804546f8.png)

**Comment by runecarlsen** [comment]
And just to be sure; 

I have reset the power meter. I have removed the devices. I have uninstalled AEOTEC app. I have re-installed the AEOTEC app, and added the Heavy Duty Switch device again. I have added a new PBTH-device for the HDS. I am using default settings. 

Waiting for the HDS to kick in and create some historic data.... this ends up; 

![image](https://user-images.githubusercontent.com/118962695/210170085-3a014547-1f06-4889-91bf-2217ea6ccaa5.png)

Same same same. 

We can even see that the PBTH device sums quite late, and it drops again to 0. 

Please help.

**Comment by runecarlsen** [comment]
And I forgot to mention, - this used to work.... I cant say I have seen this problem earlier, so it seems that something has been introduced....

**Comment by gruijter** [comment]
thx 4 all the feedback! I am aware there is a serious issue. Working on it, but it is mind boggling..... 

See the forum for updates: https://community.homey.app/t/app-pro-power-by-the-hour-insights-per-hour-day-month-and-year/20535/1152

**Comment by runecarlsen** [comment]
OK, good to know you are wokring on it. Strange ,- i have friends that DONT have this problem, so, what is it related to? All devices? Some devices? Or?

**Comment by runecarlsen** [comment]
This is still not working. I thought your latest version solved it, but it doesnt seem to be ok; 

![image](https://user-images.githubusercontent.com/118962695/210319195-c9a15ca1-bec2-4f02-a8a0-568b926fcf76.png)

**Comment by runecarlsen** [comment]
So it seems like something happend 0000 again... because it seems like something was ok around 2100, but then, back to being buggy again....

**Comment by runecarlsen** [comment]
Is there any progress on this? Still having big issues with many devices....

**Comment by gruijter** [comment]
fixed in v5
