### ISSUE TITLE
Virtual Device not possible to add - device is missing

### ISSUE THREAD

**Issue by runecarlsen** [gruijter/com.gruijter.powerhour#99]
To test a workaround for my previous posted bug, I am trying to add a virtual PBTH device... but, no good. This is what it ends up with after a while; 

![image](https://user-images.githubusercontent.com/118962695/210177742-f39d6346-52b3-44f1-bafc-283de8fc35dc.png)

So, yeah. Another bug?

**Comment by runecarlsen** [comment]
This COULD have been a workaround for the other bug, but as long as this also is a problem :(

**Comment by gruijter** [comment]
fixed in v5.0.9
Thx for reporting!

**Comment by runecarlsen** [comment]
Verified, - works! Thanks alot mate!

**Comment by runecarlsen** [comment]
I might have been too fast on my answer there, - are you sure it works as it should? Or am I misunderstanding its use? 

![image](https://user-images.githubusercontent.com/118962695/210281354-39ee2a6f-c475-4f83-82bf-c5b33ca11c3b.png)

I would expect that "this day", would also have information about the energy? Seems to only summarize for the "Energy" and not the other options? 

Rune

**Comment by gruijter** [comment]
if this is still an issue please reopen with details.
